// Code generated by ent, DO NOT EDIT.

package usagemodelsnapshot

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usagemodelsnapshot type in the database.
	Label = "usage_model_snapshot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldPricingVersion holds the string denoting the pricing_version field in the database.
	FieldPricingVersion = "pricing_version"
	// FieldDisplayInputCost holds the string denoting the display_input_cost field in the database.
	FieldDisplayInputCost = "display_input_cost"
	// FieldDisplayOutputCost holds the string denoting the display_output_cost field in the database.
	FieldDisplayOutputCost = "display_output_cost"
	// FieldDisplayCacheReadCost holds the string denoting the display_cache_read_cost field in the database.
	FieldDisplayCacheReadCost = "display_cache_read_cost"
	// FieldDisplayCacheWriteCost holds the string denoting the display_cache_write_cost field in the database.
	FieldDisplayCacheWriteCost = "display_cache_write_cost"
	// FieldDisplayTotalCost holds the string denoting the display_total_cost field in the database.
	FieldDisplayTotalCost = "display_total_cost"
	// FieldDisplayBlendCost holds the string denoting the display_blend_cost field in the database.
	FieldDisplayBlendCost = "display_blend_cost"
	// FieldCostInput holds the string denoting the cost_input field in the database.
	FieldCostInput = "cost_input"
	// FieldCostOutput holds the string denoting the cost_output field in the database.
	FieldCostOutput = "cost_output"
	// FieldCostCacheRead holds the string denoting the cost_cache_read field in the database.
	FieldCostCacheRead = "cost_cache_read"
	// FieldCostCacheWrite holds the string denoting the cost_cache_write field in the database.
	FieldCostCacheWrite = "cost_cache_write"
	// FieldCostTotal holds the string denoting the cost_total field in the database.
	FieldCostTotal = "cost_total"
	// FieldCostSupplierCode holds the string denoting the cost_supplier_code field in the database.
	FieldCostSupplierCode = "cost_supplier_code"
	// FieldInputTokens holds the string denoting the input_tokens field in the database.
	FieldInputTokens = "input_tokens"
	// FieldOutputTokens holds the string denoting the output_tokens field in the database.
	FieldOutputTokens = "output_tokens"
	// FieldCacheReadTokens holds the string denoting the cache_read_tokens field in the database.
	FieldCacheReadTokens = "cache_read_tokens"
	// FieldCacheWriteTokens holds the string denoting the cache_write_tokens field in the database.
	FieldCacheWriteTokens = "cache_write_tokens"
	// FieldUsageModelPct holds the string denoting the usage_model_pct field in the database.
	FieldUsageModelPct = "usage_model_pct"
	// Table holds the table name of the usagemodelsnapshot in the database.
	Table = "usage_model_snapshots"
)

// Columns holds all SQL columns for usagemodelsnapshot fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldUserID,
	FieldModel,
	FieldPricingVersion,
	FieldDisplayInputCost,
	FieldDisplayOutputCost,
	FieldDisplayCacheReadCost,
	FieldDisplayCacheWriteCost,
	FieldDisplayTotalCost,
	FieldDisplayBlendCost,
	FieldCostInput,
	FieldCostOutput,
	FieldCostCacheRead,
	FieldCostCacheWrite,
	FieldCostTotal,
	FieldCostSupplierCode,
	FieldInputTokens,
	FieldOutputTokens,
	FieldCacheReadTokens,
	FieldCacheWriteTokens,
	FieldUsageModelPct,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
	// ModelValidator is a validator for the "model" field. It is called by the builders before save.
	ModelValidator func(string) error
	// DefaultPricingVersion holds the default value on creation for the "pricing_version" field.
	DefaultPricingVersion int
	// DefaultDisplayInputCost holds the default value on creation for the "display_input_cost" field.
	DefaultDisplayInputCost float64
	// DefaultDisplayOutputCost holds the default value on creation for the "display_output_cost" field.
	DefaultDisplayOutputCost float64
	// DefaultDisplayCacheReadCost holds the default value on creation for the "display_cache_read_cost" field.
	DefaultDisplayCacheReadCost float64
	// DefaultDisplayCacheWriteCost holds the default value on creation for the "display_cache_write_cost" field.
	DefaultDisplayCacheWriteCost float64
	// DefaultDisplayTotalCost holds the default value on creation for the "display_total_cost" field.
	DefaultDisplayTotalCost float64
	// DefaultDisplayBlendCost holds the default value on creation for the "display_blend_cost" field.
	DefaultDisplayBlendCost float64
	// DefaultCostInput holds the default value on creation for the "cost_input" field.
	DefaultCostInput float64
	// DefaultCostOutput holds the default value on creation for the "cost_output" field.
	DefaultCostOutput float64
	// DefaultCostCacheRead holds the default value on creation for the "cost_cache_read" field.
	DefaultCostCacheRead float64
	// DefaultCostCacheWrite holds the default value on creation for the "cost_cache_write" field.
	DefaultCostCacheWrite float64
	// DefaultCostTotal holds the default value on creation for the "cost_total" field.
	DefaultCostTotal float64
	// DefaultCostSupplierCode holds the default value on creation for the "cost_supplier_code" field.
	DefaultCostSupplierCode string
	// CostSupplierCodeValidator is a validator for the "cost_supplier_code" field. It is called by the builders before save.
	CostSupplierCodeValidator func(string) error
	// DefaultInputTokens holds the default value on creation for the "input_tokens" field.
	DefaultInputTokens int64
	// DefaultOutputTokens holds the default value on creation for the "output_tokens" field.
	DefaultOutputTokens int64
	// DefaultCacheReadTokens holds the default value on creation for the "cache_read_tokens" field.
	DefaultCacheReadTokens int64
	// DefaultCacheWriteTokens holds the default value on creation for the "cache_write_tokens" field.
	DefaultCacheWriteTokens int64
	// DefaultUsageModelPct holds the default value on creation for the "usage_model_pct" field.
	DefaultUsageModelPct float64
)

// OrderOption defines the ordering options for the UsageModelSnapshot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// ByPricingVersion orders the results by the pricing_version field.
func ByPricingVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPricingVersion, opts...).ToFunc()
}

// ByDisplayInputCost orders the results by the display_input_cost field.
func ByDisplayInputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayInputCost, opts...).ToFunc()
}

// ByDisplayOutputCost orders the results by the display_output_cost field.
func ByDisplayOutputCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayOutputCost, opts...).ToFunc()
}

// ByDisplayCacheReadCost orders the results by the display_cache_read_cost field.
func ByDisplayCacheReadCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayCacheReadCost, opts...).ToFunc()
}

// ByDisplayCacheWriteCost orders the results by the display_cache_write_cost field.
func ByDisplayCacheWriteCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayCacheWriteCost, opts...).ToFunc()
}

// ByDisplayTotalCost orders the results by the display_total_cost field.
func ByDisplayTotalCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayTotalCost, opts...).ToFunc()
}

// ByDisplayBlendCost orders the results by the display_blend_cost field.
func ByDisplayBlendCost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayBlendCost, opts...).ToFunc()
}

// ByCostInput orders the results by the cost_input field.
func ByCostInput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostInput, opts...).ToFunc()
}

// ByCostOutput orders the results by the cost_output field.
func ByCostOutput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostOutput, opts...).ToFunc()
}

// ByCostCacheRead orders the results by the cost_cache_read field.
func ByCostCacheRead(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostCacheRead, opts...).ToFunc()
}

// ByCostCacheWrite orders the results by the cost_cache_write field.
func ByCostCacheWrite(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostCacheWrite, opts...).ToFunc()
}

// ByCostTotal orders the results by the cost_total field.
func ByCostTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostTotal, opts...).ToFunc()
}

// ByCostSupplierCode orders the results by the cost_supplier_code field.
func ByCostSupplierCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostSupplierCode, opts...).ToFunc()
}

// ByInputTokens orders the results by the input_tokens field.
func ByInputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputTokens, opts...).ToFunc()
}

// ByOutputTokens orders the results by the output_tokens field.
func ByOutputTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputTokens, opts...).ToFunc()
}

// ByCacheReadTokens orders the results by the cache_read_tokens field.
func ByCacheReadTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheReadTokens, opts...).ToFunc()
}

// ByCacheWriteTokens orders the results by the cache_write_tokens field.
func ByCacheWriteTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCacheWriteTokens, opts...).ToFunc()
}

// ByUsageModelPct orders the results by the usage_model_pct field.
func ByUsageModelPct(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageModelPct, opts...).ToFunc()
}
