// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeymodelscope"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ApiKeyModelScopeUpdate is the builder for updating ApiKeyModelScope entities.
type ApiKeyModelScopeUpdate struct {
	config
	hooks    []Hook
	mutation *ApiKeyModelScopeMutation
}

// Where appends a list predicates to the ApiKeyModelScopeUpdate builder.
func (_u *ApiKeyModelScopeUpdate) Where(ps ...predicate.ApiKeyModelScope) *ApiKeyModelScopeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApiKeyModelScopeUpdate) SetUpdatedAt(v time.Time) *ApiKeyModelScopeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ApiKeyModelScopeUpdate) SetAPIKeyID(v int64) *ApiKeyModelScopeUpdate {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdate) SetNillableAPIKeyID(v *int64) *ApiKeyModelScopeUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ApiKeyModelScopeUpdate) SetModelID(v string) *ApiKeyModelScopeUpdate {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdate) SetNillableModelID(v *string) *ApiKeyModelScopeUpdate {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// ClearModelID clears the value of the "model_id" field.
func (_u *ApiKeyModelScopeUpdate) ClearModelID() *ApiKeyModelScopeUpdate {
	_u.mutation.ClearModelID()
	return _u
}

// SetRateLimitPerMin sets the "rate_limit_per_min" field.
func (_u *ApiKeyModelScopeUpdate) SetRateLimitPerMin(v int) *ApiKeyModelScopeUpdate {
	_u.mutation.ResetRateLimitPerMin()
	_u.mutation.SetRateLimitPerMin(v)
	return _u
}

// SetNillableRateLimitPerMin sets the "rate_limit_per_min" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdate) SetNillableRateLimitPerMin(v *int) *ApiKeyModelScopeUpdate {
	if v != nil {
		_u.SetRateLimitPerMin(*v)
	}
	return _u
}

// AddRateLimitPerMin adds value to the "rate_limit_per_min" field.
func (_u *ApiKeyModelScopeUpdate) AddRateLimitPerMin(v int) *ApiKeyModelScopeUpdate {
	_u.mutation.AddRateLimitPerMin(v)
	return _u
}

// SetRateLimitPerHour sets the "rate_limit_per_hour" field.
func (_u *ApiKeyModelScopeUpdate) SetRateLimitPerHour(v int) *ApiKeyModelScopeUpdate {
	_u.mutation.ResetRateLimitPerHour()
	_u.mutation.SetRateLimitPerHour(v)
	return _u
}

// SetNillableRateLimitPerHour sets the "rate_limit_per_hour" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdate) SetNillableRateLimitPerHour(v *int) *ApiKeyModelScopeUpdate {
	if v != nil {
		_u.SetRateLimitPerHour(*v)
	}
	return _u
}

// AddRateLimitPerHour adds value to the "rate_limit_per_hour" field.
func (_u *ApiKeyModelScopeUpdate) AddRateLimitPerHour(v int) *ApiKeyModelScopeUpdate {
	_u.mutation.AddRateLimitPerHour(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ApiKeyModelScopeUpdate) SetEnabled(v bool) *ApiKeyModelScopeUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdate) SetNillableEnabled(v *bool) *ApiKeyModelScopeUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ApiKeyModelScopeUpdate) SetAPIKey(v *APIKey) *ApiKeyModelScopeUpdate {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the ApiKeyModelScopeMutation object of the builder.
func (_u *ApiKeyModelScopeUpdate) Mutation() *ApiKeyModelScopeMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ApiKeyModelScopeUpdate) ClearAPIKey() *ApiKeyModelScopeUpdate {
	_u.mutation.ClearAPIKey()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ApiKeyModelScopeUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyModelScopeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ApiKeyModelScopeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyModelScopeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiKeyModelScopeUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeymodelscope.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyModelScopeUpdate) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKeyModelScope.api_key"`)
	}
	return nil
}

func (_u *ApiKeyModelScopeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeymodelscope.Table, apikeymodelscope.Columns, sqlgraph.NewFieldSpec(apikeymodelscope.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeymodelscope.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(apikeymodelscope.FieldModelID, field.TypeString, value)
	}
	if _u.mutation.ModelIDCleared() {
		_spec.ClearField(apikeymodelscope.FieldModelID, field.TypeString)
	}
	if value, ok := _u.mutation.RateLimitPerMin(); ok {
		_spec.SetField(apikeymodelscope.FieldRateLimitPerMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimitPerMin(); ok {
		_spec.AddField(apikeymodelscope.FieldRateLimitPerMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateLimitPerHour(); ok {
		_spec.SetField(apikeymodelscope.FieldRateLimitPerHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimitPerHour(); ok {
		_spec.AddField(apikeymodelscope.FieldRateLimitPerHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(apikeymodelscope.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeymodelscope.APIKeyTable,
			Columns: []string{apikeymodelscope.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeymodelscope.APIKeyTable,
			Columns: []string{apikeymodelscope.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeymodelscope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ApiKeyModelScopeUpdateOne is the builder for updating a single ApiKeyModelScope entity.
type ApiKeyModelScopeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ApiKeyModelScopeMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ApiKeyModelScopeUpdateOne) SetUpdatedAt(v time.Time) *ApiKeyModelScopeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *ApiKeyModelScopeUpdateOne) SetAPIKeyID(v int64) *ApiKeyModelScopeUpdateOne {
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdateOne) SetNillableAPIKeyID(v *int64) *ApiKeyModelScopeUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// SetModelID sets the "model_id" field.
func (_u *ApiKeyModelScopeUpdateOne) SetModelID(v string) *ApiKeyModelScopeUpdateOne {
	_u.mutation.SetModelID(v)
	return _u
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdateOne) SetNillableModelID(v *string) *ApiKeyModelScopeUpdateOne {
	if v != nil {
		_u.SetModelID(*v)
	}
	return _u
}

// ClearModelID clears the value of the "model_id" field.
func (_u *ApiKeyModelScopeUpdateOne) ClearModelID() *ApiKeyModelScopeUpdateOne {
	_u.mutation.ClearModelID()
	return _u
}

// SetRateLimitPerMin sets the "rate_limit_per_min" field.
func (_u *ApiKeyModelScopeUpdateOne) SetRateLimitPerMin(v int) *ApiKeyModelScopeUpdateOne {
	_u.mutation.ResetRateLimitPerMin()
	_u.mutation.SetRateLimitPerMin(v)
	return _u
}

// SetNillableRateLimitPerMin sets the "rate_limit_per_min" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdateOne) SetNillableRateLimitPerMin(v *int) *ApiKeyModelScopeUpdateOne {
	if v != nil {
		_u.SetRateLimitPerMin(*v)
	}
	return _u
}

// AddRateLimitPerMin adds value to the "rate_limit_per_min" field.
func (_u *ApiKeyModelScopeUpdateOne) AddRateLimitPerMin(v int) *ApiKeyModelScopeUpdateOne {
	_u.mutation.AddRateLimitPerMin(v)
	return _u
}

// SetRateLimitPerHour sets the "rate_limit_per_hour" field.
func (_u *ApiKeyModelScopeUpdateOne) SetRateLimitPerHour(v int) *ApiKeyModelScopeUpdateOne {
	_u.mutation.ResetRateLimitPerHour()
	_u.mutation.SetRateLimitPerHour(v)
	return _u
}

// SetNillableRateLimitPerHour sets the "rate_limit_per_hour" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdateOne) SetNillableRateLimitPerHour(v *int) *ApiKeyModelScopeUpdateOne {
	if v != nil {
		_u.SetRateLimitPerHour(*v)
	}
	return _u
}

// AddRateLimitPerHour adds value to the "rate_limit_per_hour" field.
func (_u *ApiKeyModelScopeUpdateOne) AddRateLimitPerHour(v int) *ApiKeyModelScopeUpdateOne {
	_u.mutation.AddRateLimitPerHour(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *ApiKeyModelScopeUpdateOne) SetEnabled(v bool) *ApiKeyModelScopeUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *ApiKeyModelScopeUpdateOne) SetNillableEnabled(v *bool) *ApiKeyModelScopeUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAPIKey sets the "api_key" edge to the APIKey entity.
func (_u *ApiKeyModelScopeUpdateOne) SetAPIKey(v *APIKey) *ApiKeyModelScopeUpdateOne {
	return _u.SetAPIKeyID(v.ID)
}

// Mutation returns the ApiKeyModelScopeMutation object of the builder.
func (_u *ApiKeyModelScopeUpdateOne) Mutation() *ApiKeyModelScopeMutation {
	return _u.mutation
}

// ClearAPIKey clears the "api_key" edge to the APIKey entity.
func (_u *ApiKeyModelScopeUpdateOne) ClearAPIKey() *ApiKeyModelScopeUpdateOne {
	_u.mutation.ClearAPIKey()
	return _u
}

// Where appends a list predicates to the ApiKeyModelScopeUpdate builder.
func (_u *ApiKeyModelScopeUpdateOne) Where(ps ...predicate.ApiKeyModelScope) *ApiKeyModelScopeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ApiKeyModelScopeUpdateOne) Select(field string, fields ...string) *ApiKeyModelScopeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ApiKeyModelScope entity.
func (_u *ApiKeyModelScopeUpdateOne) Save(ctx context.Context) (*ApiKeyModelScope, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ApiKeyModelScopeUpdateOne) SaveX(ctx context.Context) *ApiKeyModelScope {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ApiKeyModelScopeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ApiKeyModelScopeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ApiKeyModelScopeUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := apikeymodelscope.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ApiKeyModelScopeUpdateOne) check() error {
	if _u.mutation.APIKeyCleared() && len(_u.mutation.APIKeyIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ApiKeyModelScope.api_key"`)
	}
	return nil
}

func (_u *ApiKeyModelScopeUpdateOne) sqlSave(ctx context.Context) (_node *ApiKeyModelScope, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(apikeymodelscope.Table, apikeymodelscope.Columns, sqlgraph.NewFieldSpec(apikeymodelscope.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ApiKeyModelScope.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, apikeymodelscope.FieldID)
		for _, f := range fields {
			if !apikeymodelscope.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != apikeymodelscope.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(apikeymodelscope.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ModelID(); ok {
		_spec.SetField(apikeymodelscope.FieldModelID, field.TypeString, value)
	}
	if _u.mutation.ModelIDCleared() {
		_spec.ClearField(apikeymodelscope.FieldModelID, field.TypeString)
	}
	if value, ok := _u.mutation.RateLimitPerMin(); ok {
		_spec.SetField(apikeymodelscope.FieldRateLimitPerMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimitPerMin(); ok {
		_spec.AddField(apikeymodelscope.FieldRateLimitPerMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RateLimitPerHour(); ok {
		_spec.SetField(apikeymodelscope.FieldRateLimitPerHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRateLimitPerHour(); ok {
		_spec.AddField(apikeymodelscope.FieldRateLimitPerHour, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(apikeymodelscope.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.APIKeyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeymodelscope.APIKeyTable,
			Columns: []string{apikeymodelscope.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APIKeyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   apikeymodelscope.APIKeyTable,
			Columns: []string{apikeymodelscope.APIKeyColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ApiKeyModelScope{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{apikeymodelscope.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
