// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/apikey"
	"github.com/Wei-Shaw/sub2api/ent/apikeymodelscope"
)

// ApiKeyModelScope is the model entity for the ApiKeyModelScope schema.
type ApiKeyModelScope struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID *string `json:"model_id,omitempty"`
	// RateLimitPerMin holds the value of the "rate_limit_per_min" field.
	RateLimitPerMin int `json:"rate_limit_per_min,omitempty"`
	// RateLimitPerHour holds the value of the "rate_limit_per_hour" field.
	RateLimitPerHour int `json:"rate_limit_per_hour,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ApiKeyModelScopeQuery when eager-loading is set.
	Edges        ApiKeyModelScopeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ApiKeyModelScopeEdges holds the relations/edges for other nodes in the graph.
type ApiKeyModelScopeEdges struct {
	// APIKey holds the value of the api_key edge.
	APIKey *APIKey `json:"api_key,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// APIKeyOrErr returns the APIKey value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ApiKeyModelScopeEdges) APIKeyOrErr() (*APIKey, error) {
	if e.APIKey != nil {
		return e.APIKey, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: apikey.Label}
	}
	return nil, &NotLoadedError{edge: "api_key"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ApiKeyModelScope) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case apikeymodelscope.FieldEnabled:
			values[i] = new(sql.NullBool)
		case apikeymodelscope.FieldAPIKeyID, apikeymodelscope.FieldRateLimitPerMin, apikeymodelscope.FieldRateLimitPerHour:
			values[i] = new(sql.NullInt64)
		case apikeymodelscope.FieldID, apikeymodelscope.FieldModelID:
			values[i] = new(sql.NullString)
		case apikeymodelscope.FieldCreatedAt, apikeymodelscope.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ApiKeyModelScope fields.
func (_m *ApiKeyModelScope) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case apikeymodelscope.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case apikeymodelscope.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case apikeymodelscope.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case apikeymodelscope.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case apikeymodelscope.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = new(string)
				*_m.ModelID = value.String
			}
		case apikeymodelscope.FieldRateLimitPerMin:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_per_min", values[i])
			} else if value.Valid {
				_m.RateLimitPerMin = int(value.Int64)
			}
		case apikeymodelscope.FieldRateLimitPerHour:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rate_limit_per_hour", values[i])
			} else if value.Valid {
				_m.RateLimitPerHour = int(value.Int64)
			}
		case apikeymodelscope.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ApiKeyModelScope.
// This includes values selected through modifiers, order, etc.
func (_m *ApiKeyModelScope) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAPIKey queries the "api_key" edge of the ApiKeyModelScope entity.
func (_m *ApiKeyModelScope) QueryAPIKey() *APIKeyQuery {
	return NewApiKeyModelScopeClient(_m.config).QueryAPIKey(_m)
}

// Update returns a builder for updating this ApiKeyModelScope.
// Note that you need to call ApiKeyModelScope.Unwrap() before calling this method if this ApiKeyModelScope
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ApiKeyModelScope) Update() *ApiKeyModelScopeUpdateOne {
	return NewApiKeyModelScopeClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ApiKeyModelScope entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ApiKeyModelScope) Unwrap() *ApiKeyModelScope {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ApiKeyModelScope is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ApiKeyModelScope) String() string {
	var builder strings.Builder
	builder.WriteString("ApiKeyModelScope(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	if v := _m.ModelID; v != nil {
		builder.WriteString("model_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("rate_limit_per_min=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimitPerMin))
	builder.WriteString(", ")
	builder.WriteString("rate_limit_per_hour=")
	builder.WriteString(fmt.Sprintf("%v", _m.RateLimitPerHour))
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteByte(')')
	return builder.String()
}

// ApiKeyModelScopes is a parsable slice of ApiKeyModelScope.
type ApiKeyModelScopes []*ApiKeyModelScope
