// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
	"github.com/Wei-Shaw/sub2api/ent/supplierpricing"
)

// ModelCatalogCreate is the builder for creating a ModelCatalog entity.
type ModelCatalogCreate struct {
	config
	mutation *ModelCatalogMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *ModelCatalogCreate) SetCreatedAt(v time.Time) *ModelCatalogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableCreatedAt(v *time.Time) *ModelCatalogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ModelCatalogCreate) SetUpdatedAt(v time.Time) *ModelCatalogCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableUpdatedAt(v *time.Time) *ModelCatalogCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetCanonicalName sets the "canonical_name" field.
func (_c *ModelCatalogCreate) SetCanonicalName(v string) *ModelCatalogCreate {
	_c.mutation.SetCanonicalName(v)
	return _c
}

// SetPublicName sets the "public_name" field.
func (_c *ModelCatalogCreate) SetPublicName(v string) *ModelCatalogCreate {
	_c.mutation.SetPublicName(v)
	return _c
}

// SetContextWindow sets the "context_window" field.
func (_c *ModelCatalogCreate) SetContextWindow(v int64) *ModelCatalogCreate {
	_c.mutation.SetContextWindow(v)
	return _c
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableContextWindow(v *int64) *ModelCatalogCreate {
	if v != nil {
		_c.SetContextWindow(*v)
	}
	return _c
}

// SetSourceSuppliers sets the "source_suppliers" field.
func (_c *ModelCatalogCreate) SetSourceSuppliers(v []string) *ModelCatalogCreate {
	_c.mutation.SetSourceSuppliers(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ModelCatalogCreate) SetStatus(v string) *ModelCatalogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableStatus(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ModelCatalogCreate) SetID(v string) *ModelCatalogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ModelCatalogCreate) SetNillableID(v *string) *ModelCatalogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPricingIDs adds the "pricing" edge to the ModelPricing entity by IDs.
func (_c *ModelCatalogCreate) AddPricingIDs(ids ...string) *ModelCatalogCreate {
	_c.mutation.AddPricingIDs(ids...)
	return _c
}

// AddPricing adds the "pricing" edges to the ModelPricing entity.
func (_c *ModelCatalogCreate) AddPricing(v ...*ModelPricing) *ModelCatalogCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPricingIDs(ids...)
}

// AddSupplierPricingIDs adds the "supplier_pricing" edge to the SupplierPricing entity by IDs.
func (_c *ModelCatalogCreate) AddSupplierPricingIDs(ids ...string) *ModelCatalogCreate {
	_c.mutation.AddSupplierPricingIDs(ids...)
	return _c
}

// AddSupplierPricing adds the "supplier_pricing" edges to the SupplierPricing entity.
func (_c *ModelCatalogCreate) AddSupplierPricing(v ...*SupplierPricing) *ModelCatalogCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSupplierPricingIDs(ids...)
}

// Mutation returns the ModelCatalogMutation object of the builder.
func (_c *ModelCatalogCreate) Mutation() *ModelCatalogMutation {
	return _c.mutation
}

// Save creates the ModelCatalog in the database.
func (_c *ModelCatalogCreate) Save(ctx context.Context) (*ModelCatalog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ModelCatalogCreate) SaveX(ctx context.Context) *ModelCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ModelCatalogCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := modelcatalog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := modelcatalog.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := modelcatalog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := modelcatalog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ModelCatalogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ModelCatalog.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ModelCatalog.updated_at"`)}
	}
	if _, ok := _c.mutation.CanonicalName(); !ok {
		return &ValidationError{Name: "canonical_name", err: errors.New(`ent: missing required field "ModelCatalog.canonical_name"`)}
	}
	if v, ok := _c.mutation.CanonicalName(); ok {
		if err := modelcatalog.CanonicalNameValidator(v); err != nil {
			return &ValidationError{Name: "canonical_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.canonical_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublicName(); !ok {
		return &ValidationError{Name: "public_name", err: errors.New(`ent: missing required field "ModelCatalog.public_name"`)}
	}
	if v, ok := _c.mutation.PublicName(); ok {
		if err := modelcatalog.PublicNameValidator(v); err != nil {
			return &ValidationError{Name: "public_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.public_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ModelCatalog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := modelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ModelCatalogCreate) sqlSave(ctx context.Context) (*ModelCatalog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected ModelCatalog.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ModelCatalogCreate) createSpec() (*ModelCatalog, *sqlgraph.CreateSpec) {
	var (
		_node = &ModelCatalog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(modelcatalog.Table, sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(modelcatalog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalog.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.CanonicalName(); ok {
		_spec.SetField(modelcatalog.FieldCanonicalName, field.TypeString, value)
		_node.CanonicalName = value
	}
	if value, ok := _c.mutation.PublicName(); ok {
		_spec.SetField(modelcatalog.FieldPublicName, field.TypeString, value)
		_node.PublicName = value
	}
	if value, ok := _c.mutation.ContextWindow(); ok {
		_spec.SetField(modelcatalog.FieldContextWindow, field.TypeInt64, value)
		_node.ContextWindow = &value
	}
	if value, ok := _c.mutation.SourceSuppliers(); ok {
		_spec.SetField(modelcatalog.FieldSourceSuppliers, field.TypeJSON, value)
		_node.SourceSuppliers = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(modelcatalog.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.PricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.SupplierPricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalog.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogCreate) OnConflict(opts ...sql.ConflictOption) *ModelCatalogUpsertOne {
	_c.conflict = opts
	return &ModelCatalogUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogCreate) OnConflictColumns(columns ...string) *ModelCatalogUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogUpsertOne{
		create: _c,
	}
}

type (
	// ModelCatalogUpsertOne is the builder for "upsert"-ing
	//  one ModelCatalog node.
	ModelCatalogUpsertOne struct {
		create *ModelCatalogCreate
	}

	// ModelCatalogUpsert is the "OnConflict" setter.
	ModelCatalogUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogUpsert) SetUpdatedAt(v time.Time) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateUpdatedAt() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldUpdatedAt)
	return u
}

// SetCanonicalName sets the "canonical_name" field.
func (u *ModelCatalogUpsert) SetCanonicalName(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldCanonicalName, v)
	return u
}

// UpdateCanonicalName sets the "canonical_name" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateCanonicalName() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldCanonicalName)
	return u
}

// SetPublicName sets the "public_name" field.
func (u *ModelCatalogUpsert) SetPublicName(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldPublicName, v)
	return u
}

// UpdatePublicName sets the "public_name" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdatePublicName() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldPublicName)
	return u
}

// SetContextWindow sets the "context_window" field.
func (u *ModelCatalogUpsert) SetContextWindow(v int64) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldContextWindow, v)
	return u
}

// UpdateContextWindow sets the "context_window" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateContextWindow() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldContextWindow)
	return u
}

// AddContextWindow adds v to the "context_window" field.
func (u *ModelCatalogUpsert) AddContextWindow(v int64) *ModelCatalogUpsert {
	u.Add(modelcatalog.FieldContextWindow, v)
	return u
}

// ClearContextWindow clears the value of the "context_window" field.
func (u *ModelCatalogUpsert) ClearContextWindow() *ModelCatalogUpsert {
	u.SetNull(modelcatalog.FieldContextWindow)
	return u
}

// SetSourceSuppliers sets the "source_suppliers" field.
func (u *ModelCatalogUpsert) SetSourceSuppliers(v []string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldSourceSuppliers, v)
	return u
}

// UpdateSourceSuppliers sets the "source_suppliers" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateSourceSuppliers() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldSourceSuppliers)
	return u
}

// ClearSourceSuppliers clears the value of the "source_suppliers" field.
func (u *ModelCatalogUpsert) ClearSourceSuppliers() *ModelCatalogUpsert {
	u.SetNull(modelcatalog.FieldSourceSuppliers)
	return u
}

// SetStatus sets the "status" field.
func (u *ModelCatalogUpsert) SetStatus(v string) *ModelCatalogUpsert {
	u.Set(modelcatalog.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelCatalogUpsert) UpdateStatus() *ModelCatalogUpsert {
	u.SetExcluded(modelcatalog.FieldStatus)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(modelcatalog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ModelCatalogUpsertOne) UpdateNewValues() *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(modelcatalog.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(modelcatalog.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ModelCatalogUpsertOne) Ignore() *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogUpsertOne) DoNothing() *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogCreate.OnConflict
// documentation for more info.
func (u *ModelCatalogUpsertOne) Update(set func(*ModelCatalogUpsert)) *ModelCatalogUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogUpsertOne) SetUpdatedAt(v time.Time) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateUpdatedAt() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCanonicalName sets the "canonical_name" field.
func (u *ModelCatalogUpsertOne) SetCanonicalName(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetCanonicalName(v)
	})
}

// UpdateCanonicalName sets the "canonical_name" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateCanonicalName() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateCanonicalName()
	})
}

// SetPublicName sets the "public_name" field.
func (u *ModelCatalogUpsertOne) SetPublicName(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetPublicName(v)
	})
}

// UpdatePublicName sets the "public_name" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdatePublicName() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdatePublicName()
	})
}

// SetContextWindow sets the "context_window" field.
func (u *ModelCatalogUpsertOne) SetContextWindow(v int64) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetContextWindow(v)
	})
}

// AddContextWindow adds v to the "context_window" field.
func (u *ModelCatalogUpsertOne) AddContextWindow(v int64) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.AddContextWindow(v)
	})
}

// UpdateContextWindow sets the "context_window" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateContextWindow() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateContextWindow()
	})
}

// ClearContextWindow clears the value of the "context_window" field.
func (u *ModelCatalogUpsertOne) ClearContextWindow() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearContextWindow()
	})
}

// SetSourceSuppliers sets the "source_suppliers" field.
func (u *ModelCatalogUpsertOne) SetSourceSuppliers(v []string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetSourceSuppliers(v)
	})
}

// UpdateSourceSuppliers sets the "source_suppliers" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateSourceSuppliers() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateSourceSuppliers()
	})
}

// ClearSourceSuppliers clears the value of the "source_suppliers" field.
func (u *ModelCatalogUpsertOne) ClearSourceSuppliers() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearSourceSuppliers()
	})
}

// SetStatus sets the "status" field.
func (u *ModelCatalogUpsertOne) SetStatus(v string) *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelCatalogUpsertOne) UpdateStatus() *ModelCatalogUpsertOne {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *ModelCatalogUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ModelCatalogUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: ModelCatalogUpsertOne.ID is not supported by MySQL driver. Use ModelCatalogUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ModelCatalogUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ModelCatalogCreateBulk is the builder for creating many ModelCatalog entities in bulk.
type ModelCatalogCreateBulk struct {
	config
	err      error
	builders []*ModelCatalogCreate
	conflict []sql.ConflictOption
}

// Save creates the ModelCatalog entities in the database.
func (_c *ModelCatalogCreateBulk) Save(ctx context.Context) ([]*ModelCatalog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ModelCatalog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ModelCatalogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ModelCatalogCreateBulk) SaveX(ctx context.Context) []*ModelCatalog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ModelCatalogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ModelCatalogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ModelCatalog.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ModelCatalogUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *ModelCatalogCreateBulk) OnConflict(opts ...sql.ConflictOption) *ModelCatalogUpsertBulk {
	_c.conflict = opts
	return &ModelCatalogUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ModelCatalogCreateBulk) OnConflictColumns(columns ...string) *ModelCatalogUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ModelCatalogUpsertBulk{
		create: _c,
	}
}

// ModelCatalogUpsertBulk is the builder for "upsert"-ing
// a bulk of ModelCatalog nodes.
type ModelCatalogUpsertBulk struct {
	create *ModelCatalogCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(modelcatalog.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *ModelCatalogUpsertBulk) UpdateNewValues() *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(modelcatalog.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(modelcatalog.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ModelCatalog.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ModelCatalogUpsertBulk) Ignore() *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ModelCatalogUpsertBulk) DoNothing() *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ModelCatalogCreateBulk.OnConflict
// documentation for more info.
func (u *ModelCatalogUpsertBulk) Update(set func(*ModelCatalogUpsert)) *ModelCatalogUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ModelCatalogUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *ModelCatalogUpsertBulk) SetUpdatedAt(v time.Time) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateUpdatedAt() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetCanonicalName sets the "canonical_name" field.
func (u *ModelCatalogUpsertBulk) SetCanonicalName(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetCanonicalName(v)
	})
}

// UpdateCanonicalName sets the "canonical_name" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateCanonicalName() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateCanonicalName()
	})
}

// SetPublicName sets the "public_name" field.
func (u *ModelCatalogUpsertBulk) SetPublicName(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetPublicName(v)
	})
}

// UpdatePublicName sets the "public_name" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdatePublicName() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdatePublicName()
	})
}

// SetContextWindow sets the "context_window" field.
func (u *ModelCatalogUpsertBulk) SetContextWindow(v int64) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetContextWindow(v)
	})
}

// AddContextWindow adds v to the "context_window" field.
func (u *ModelCatalogUpsertBulk) AddContextWindow(v int64) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.AddContextWindow(v)
	})
}

// UpdateContextWindow sets the "context_window" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateContextWindow() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateContextWindow()
	})
}

// ClearContextWindow clears the value of the "context_window" field.
func (u *ModelCatalogUpsertBulk) ClearContextWindow() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearContextWindow()
	})
}

// SetSourceSuppliers sets the "source_suppliers" field.
func (u *ModelCatalogUpsertBulk) SetSourceSuppliers(v []string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetSourceSuppliers(v)
	})
}

// UpdateSourceSuppliers sets the "source_suppliers" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateSourceSuppliers() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateSourceSuppliers()
	})
}

// ClearSourceSuppliers clears the value of the "source_suppliers" field.
func (u *ModelCatalogUpsertBulk) ClearSourceSuppliers() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.ClearSourceSuppliers()
	})
}

// SetStatus sets the "status" field.
func (u *ModelCatalogUpsertBulk) SetStatus(v string) *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ModelCatalogUpsertBulk) UpdateStatus() *ModelCatalogUpsertBulk {
	return u.Update(func(s *ModelCatalogUpsert) {
		s.UpdateStatus()
	})
}

// Exec executes the query.
func (u *ModelCatalogUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ModelCatalogCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ModelCatalogCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ModelCatalogUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
