// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelbalance"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
)

// ModelBalance is the model entity for the ModelBalance schema.
type ModelBalance struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID string `json:"model_id,omitempty"`
	// TokensPurchased holds the value of the "tokens_purchased" field.
	TokensPurchased int64 `json:"tokens_purchased,omitempty"`
	// TokensConsumed holds the value of the "tokens_consumed" field.
	TokensConsumed int64 `json:"tokens_consumed,omitempty"`
	// Balance holds the value of the "balance" field.
	Balance int64 `json:"balance,omitempty"`
	// UsagePercent holds the value of the "usage_percent" field.
	UsagePercent float64 `json:"usage_percent,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelBalanceQuery when eager-loading is set.
	Edges        ModelBalanceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelBalanceEdges holds the relations/edges for other nodes in the graph.
type ModelBalanceEdges struct {
	// Model holds the value of the model edge.
	Model *ModelCatalog `json:"model,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModelOrErr returns the Model value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelBalanceEdges) ModelOrErr() (*ModelCatalog, error) {
	if e.Model != nil {
		return e.Model, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: modelcatalog.Label}
	}
	return nil, &NotLoadedError{edge: "model"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelBalance) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelbalance.FieldUsagePercent:
			values[i] = new(sql.NullFloat64)
		case modelbalance.FieldUserID, modelbalance.FieldTokensPurchased, modelbalance.FieldTokensConsumed, modelbalance.FieldBalance, modelbalance.FieldVersion:
			values[i] = new(sql.NullInt64)
		case modelbalance.FieldID, modelbalance.FieldModelID, modelbalance.FieldStatus:
			values[i] = new(sql.NullString)
		case modelbalance.FieldCreatedAt, modelbalance.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelBalance fields.
func (_m *ModelBalance) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelbalance.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case modelbalance.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case modelbalance.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case modelbalance.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case modelbalance.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = value.String
			}
		case modelbalance.FieldTokensPurchased:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_purchased", values[i])
			} else if value.Valid {
				_m.TokensPurchased = value.Int64
			}
		case modelbalance.FieldTokensConsumed:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_consumed", values[i])
			} else if value.Valid {
				_m.TokensConsumed = value.Int64
			}
		case modelbalance.FieldBalance:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance", values[i])
			} else if value.Valid {
				_m.Balance = value.Int64
			}
		case modelbalance.FieldUsagePercent:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field usage_percent", values[i])
			} else if value.Valid {
				_m.UsagePercent = value.Float64
			}
		case modelbalance.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case modelbalance.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelBalance.
// This includes values selected through modifiers, order, etc.
func (_m *ModelBalance) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModel queries the "model" edge of the ModelBalance entity.
func (_m *ModelBalance) QueryModel() *ModelCatalogQuery {
	return NewModelBalanceClient(_m.config).QueryModel(_m)
}

// Update returns a builder for updating this ModelBalance.
// Note that you need to call ModelBalance.Unwrap() before calling this method if this ModelBalance
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelBalance) Update() *ModelBalanceUpdateOne {
	return NewModelBalanceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelBalance entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelBalance) Unwrap() *ModelBalance {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelBalance is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelBalance) String() string {
	var builder strings.Builder
	builder.WriteString("ModelBalance(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("model_id=")
	builder.WriteString(_m.ModelID)
	builder.WriteString(", ")
	builder.WriteString("tokens_purchased=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokensPurchased))
	builder.WriteString(", ")
	builder.WriteString("tokens_consumed=")
	builder.WriteString(fmt.Sprintf("%v", _m.TokensConsumed))
	builder.WriteString(", ")
	builder.WriteString("balance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Balance))
	builder.WriteString(", ")
	builder.WriteString("usage_percent=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsagePercent))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteByte(')')
	return builder.String()
}

// ModelBalances is a parsable slice of ModelBalance.
type ModelBalances []*ModelBalance
