// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
)

// ModelPricing is the model entity for the ModelPricing schema.
type ModelPricing struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// ModelID holds the value of the "model_id" field.
	ModelID *string `json:"model_id,omitempty"`
	// Version holds the value of the "version" field.
	Version int `json:"version,omitempty"`
	// InputRate holds the value of the "input_rate" field.
	InputRate *float64 `json:"input_rate,omitempty"`
	// OutputRate holds the value of the "output_rate" field.
	OutputRate *float64 `json:"output_rate,omitempty"`
	// CachedReadRate holds the value of the "cached_read_rate" field.
	CachedReadRate *float64 `json:"cached_read_rate,omitempty"`
	// CachedWriteRate holds the value of the "cached_write_rate" field.
	CachedWriteRate *float64 `json:"cached_write_rate,omitempty"`
	// ContextTier holds the value of the "context_tier" field.
	ContextTier *string `json:"context_tier,omitempty"`
	// TokensPerDollar holds the value of the "tokens_per_dollar" field.
	TokensPerDollar *int64 `json:"tokens_per_dollar,omitempty"`
	// PctPer1mTokens holds the value of the "pct_per_1m_tokens" field.
	PctPer1mTokens *float64 `json:"pct_per_1m_tokens,omitempty"`
	// EffectiveFrom holds the value of the "effective_from" field.
	EffectiveFrom *time.Time `json:"effective_from,omitempty"`
	// EffectiveTo holds the value of the "effective_to" field.
	EffectiveTo *time.Time `json:"effective_to,omitempty"`
	// SourceRef holds the value of the "source_ref" field.
	SourceRef *string `json:"source_ref,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModelPricingQuery when eager-loading is set.
	Edges        ModelPricingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModelPricingEdges holds the relations/edges for other nodes in the graph.
type ModelPricingEdges struct {
	// Model holds the value of the model edge.
	Model *ModelCatalog `json:"model,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ModelOrErr returns the Model value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModelPricingEdges) ModelOrErr() (*ModelCatalog, error) {
	if e.Model != nil {
		return e.Model, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: modelcatalog.Label}
	}
	return nil, &NotLoadedError{edge: "model"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModelPricing) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modelpricing.FieldInputRate, modelpricing.FieldOutputRate, modelpricing.FieldCachedReadRate, modelpricing.FieldCachedWriteRate, modelpricing.FieldPctPer1mTokens:
			values[i] = new(sql.NullFloat64)
		case modelpricing.FieldVersion, modelpricing.FieldTokensPerDollar:
			values[i] = new(sql.NullInt64)
		case modelpricing.FieldID, modelpricing.FieldModelID, modelpricing.FieldContextTier, modelpricing.FieldSourceRef:
			values[i] = new(sql.NullString)
		case modelpricing.FieldEffectiveFrom, modelpricing.FieldEffectiveTo:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModelPricing fields.
func (_m *ModelPricing) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modelpricing.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case modelpricing.FieldModelID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model_id", values[i])
			} else if value.Valid {
				_m.ModelID = new(string)
				*_m.ModelID = value.String
			}
		case modelpricing.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = int(value.Int64)
			}
		case modelpricing.FieldInputRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field input_rate", values[i])
			} else if value.Valid {
				_m.InputRate = new(float64)
				*_m.InputRate = value.Float64
			}
		case modelpricing.FieldOutputRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field output_rate", values[i])
			} else if value.Valid {
				_m.OutputRate = new(float64)
				*_m.OutputRate = value.Float64
			}
		case modelpricing.FieldCachedReadRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_read_rate", values[i])
			} else if value.Valid {
				_m.CachedReadRate = new(float64)
				*_m.CachedReadRate = value.Float64
			}
		case modelpricing.FieldCachedWriteRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cached_write_rate", values[i])
			} else if value.Valid {
				_m.CachedWriteRate = new(float64)
				*_m.CachedWriteRate = value.Float64
			}
		case modelpricing.FieldContextTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field context_tier", values[i])
			} else if value.Valid {
				_m.ContextTier = new(string)
				*_m.ContextTier = value.String
			}
		case modelpricing.FieldTokensPerDollar:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field tokens_per_dollar", values[i])
			} else if value.Valid {
				_m.TokensPerDollar = new(int64)
				*_m.TokensPerDollar = value.Int64
			}
		case modelpricing.FieldPctPer1mTokens:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field pct_per_1m_tokens", values[i])
			} else if value.Valid {
				_m.PctPer1mTokens = new(float64)
				*_m.PctPer1mTokens = value.Float64
			}
		case modelpricing.FieldEffectiveFrom:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_from", values[i])
			} else if value.Valid {
				_m.EffectiveFrom = new(time.Time)
				*_m.EffectiveFrom = value.Time
			}
		case modelpricing.FieldEffectiveTo:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field effective_to", values[i])
			} else if value.Valid {
				_m.EffectiveTo = new(time.Time)
				*_m.EffectiveTo = value.Time
			}
		case modelpricing.FieldSourceRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_ref", values[i])
			} else if value.Valid {
				_m.SourceRef = new(string)
				*_m.SourceRef = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModelPricing.
// This includes values selected through modifiers, order, etc.
func (_m *ModelPricing) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryModel queries the "model" edge of the ModelPricing entity.
func (_m *ModelPricing) QueryModel() *ModelCatalogQuery {
	return NewModelPricingClient(_m.config).QueryModel(_m)
}

// Update returns a builder for updating this ModelPricing.
// Note that you need to call ModelPricing.Unwrap() before calling this method if this ModelPricing
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModelPricing) Update() *ModelPricingUpdateOne {
	return NewModelPricingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModelPricing entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModelPricing) Unwrap() *ModelPricing {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModelPricing is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModelPricing) String() string {
	var builder strings.Builder
	builder.WriteString("ModelPricing(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ModelID; v != nil {
		builder.WriteString("model_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	if v := _m.InputRate; v != nil {
		builder.WriteString("input_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.OutputRate; v != nil {
		builder.WriteString("output_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CachedReadRate; v != nil {
		builder.WriteString("cached_read_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CachedWriteRate; v != nil {
		builder.WriteString("cached_write_rate=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ContextTier; v != nil {
		builder.WriteString("context_tier=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TokensPerDollar; v != nil {
		builder.WriteString("tokens_per_dollar=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PctPer1mTokens; v != nil {
		builder.WriteString("pct_per_1m_tokens=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.EffectiveFrom; v != nil {
		builder.WriteString("effective_from=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EffectiveTo; v != nil {
		builder.WriteString("effective_to=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.SourceRef; v != nil {
		builder.WriteString("source_ref=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModelPricings is a parsable slice of ModelPricing.
type ModelPricings []*ModelPricing
