// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelbalance"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/modelpricing"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supplierpricing"
)

// ModelCatalogUpdate is the builder for updating ModelCatalog entities.
type ModelCatalogUpdate struct {
	config
	hooks    []Hook
	mutation *ModelCatalogMutation
}

// Where appends a list predicates to the ModelCatalogUpdate builder.
func (_u *ModelCatalogUpdate) Where(ps ...predicate.ModelCatalog) *ModelCatalogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogUpdate) SetUpdatedAt(v time.Time) *ModelCatalogUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCanonicalName sets the "canonical_name" field.
func (_u *ModelCatalogUpdate) SetCanonicalName(v string) *ModelCatalogUpdate {
	_u.mutation.SetCanonicalName(v)
	return _u
}

// SetNillableCanonicalName sets the "canonical_name" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableCanonicalName(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetCanonicalName(*v)
	}
	return _u
}

// SetPublicName sets the "public_name" field.
func (_u *ModelCatalogUpdate) SetPublicName(v string) *ModelCatalogUpdate {
	_u.mutation.SetPublicName(v)
	return _u
}

// SetNillablePublicName sets the "public_name" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillablePublicName(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetPublicName(*v)
	}
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *ModelCatalogUpdate) SetContextWindow(v int64) *ModelCatalogUpdate {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableContextWindow(v *int64) *ModelCatalogUpdate {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *ModelCatalogUpdate) AddContextWindow(v int64) *ModelCatalogUpdate {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *ModelCatalogUpdate) ClearContextWindow() *ModelCatalogUpdate {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetSourceSuppliers sets the "source_suppliers" field.
func (_u *ModelCatalogUpdate) SetSourceSuppliers(v []string) *ModelCatalogUpdate {
	_u.mutation.SetSourceSuppliers(v)
	return _u
}

// AppendSourceSuppliers appends value to the "source_suppliers" field.
func (_u *ModelCatalogUpdate) AppendSourceSuppliers(v []string) *ModelCatalogUpdate {
	_u.mutation.AppendSourceSuppliers(v)
	return _u
}

// ClearSourceSuppliers clears the value of the "source_suppliers" field.
func (_u *ModelCatalogUpdate) ClearSourceSuppliers() *ModelCatalogUpdate {
	_u.mutation.ClearSourceSuppliers()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogUpdate) SetStatus(v string) *ModelCatalogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogUpdate) SetNillableStatus(v *string) *ModelCatalogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddPricingIDs adds the "pricing" edge to the ModelPricing entity by IDs.
func (_u *ModelCatalogUpdate) AddPricingIDs(ids ...string) *ModelCatalogUpdate {
	_u.mutation.AddPricingIDs(ids...)
	return _u
}

// AddPricing adds the "pricing" edges to the ModelPricing entity.
func (_u *ModelCatalogUpdate) AddPricing(v ...*ModelPricing) *ModelCatalogUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPricingIDs(ids...)
}

// AddSupplierPricingIDs adds the "supplier_pricing" edge to the SupplierPricing entity by IDs.
func (_u *ModelCatalogUpdate) AddSupplierPricingIDs(ids ...string) *ModelCatalogUpdate {
	_u.mutation.AddSupplierPricingIDs(ids...)
	return _u
}

// AddSupplierPricing adds the "supplier_pricing" edges to the SupplierPricing entity.
func (_u *ModelCatalogUpdate) AddSupplierPricing(v ...*SupplierPricing) *ModelCatalogUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSupplierPricingIDs(ids...)
}

// AddBalanceIDs adds the "balances" edge to the ModelBalance entity by IDs.
func (_u *ModelCatalogUpdate) AddBalanceIDs(ids ...string) *ModelCatalogUpdate {
	_u.mutation.AddBalanceIDs(ids...)
	return _u
}

// AddBalances adds the "balances" edges to the ModelBalance entity.
func (_u *ModelCatalogUpdate) AddBalances(v ...*ModelBalance) *ModelCatalogUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBalanceIDs(ids...)
}

// Mutation returns the ModelCatalogMutation object of the builder.
func (_u *ModelCatalogUpdate) Mutation() *ModelCatalogMutation {
	return _u.mutation
}

// ClearPricing clears all "pricing" edges to the ModelPricing entity.
func (_u *ModelCatalogUpdate) ClearPricing() *ModelCatalogUpdate {
	_u.mutation.ClearPricing()
	return _u
}

// RemovePricingIDs removes the "pricing" edge to ModelPricing entities by IDs.
func (_u *ModelCatalogUpdate) RemovePricingIDs(ids ...string) *ModelCatalogUpdate {
	_u.mutation.RemovePricingIDs(ids...)
	return _u
}

// RemovePricing removes "pricing" edges to ModelPricing entities.
func (_u *ModelCatalogUpdate) RemovePricing(v ...*ModelPricing) *ModelCatalogUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePricingIDs(ids...)
}

// ClearSupplierPricing clears all "supplier_pricing" edges to the SupplierPricing entity.
func (_u *ModelCatalogUpdate) ClearSupplierPricing() *ModelCatalogUpdate {
	_u.mutation.ClearSupplierPricing()
	return _u
}

// RemoveSupplierPricingIDs removes the "supplier_pricing" edge to SupplierPricing entities by IDs.
func (_u *ModelCatalogUpdate) RemoveSupplierPricingIDs(ids ...string) *ModelCatalogUpdate {
	_u.mutation.RemoveSupplierPricingIDs(ids...)
	return _u
}

// RemoveSupplierPricing removes "supplier_pricing" edges to SupplierPricing entities.
func (_u *ModelCatalogUpdate) RemoveSupplierPricing(v ...*SupplierPricing) *ModelCatalogUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSupplierPricingIDs(ids...)
}

// ClearBalances clears all "balances" edges to the ModelBalance entity.
func (_u *ModelCatalogUpdate) ClearBalances() *ModelCatalogUpdate {
	_u.mutation.ClearBalances()
	return _u
}

// RemoveBalanceIDs removes the "balances" edge to ModelBalance entities by IDs.
func (_u *ModelCatalogUpdate) RemoveBalanceIDs(ids ...string) *ModelCatalogUpdate {
	_u.mutation.RemoveBalanceIDs(ids...)
	return _u
}

// RemoveBalances removes "balances" edges to ModelBalance entities.
func (_u *ModelCatalogUpdate) RemoveBalances(v ...*ModelBalance) *ModelCatalogUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBalanceIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModelCatalogUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModelCatalogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogUpdate) check() error {
	if v, ok := _u.mutation.CanonicalName(); ok {
		if err := modelcatalog.CanonicalNameValidator(v); err != nil {
			return &ValidationError{Name: "canonical_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.canonical_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicName(); ok {
		if err := modelcatalog.PublicNameValidator(v); err != nil {
			return &ValidationError{Name: "public_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.public_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalog.Table, modelcatalog.Columns, sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CanonicalName(); ok {
		_spec.SetField(modelcatalog.FieldCanonicalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicName(); ok {
		_spec.SetField(modelcatalog.FieldPublicName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(modelcatalog.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(modelcatalog.FieldContextWindow, field.TypeInt64, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(modelcatalog.FieldContextWindow, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceSuppliers(); ok {
		_spec.SetField(modelcatalog.FieldSourceSuppliers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSourceSuppliers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalog.FieldSourceSuppliers, value)
		})
	}
	if _u.mutation.SourceSuppliersCleared() {
		_spec.ClearField(modelcatalog.FieldSourceSuppliers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalog.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.PricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricingIDs(); len(nodes) > 0 && !_u.mutation.PricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupplierPricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSupplierPricingIDs(); len(nodes) > 0 && !_u.mutation.SupplierPricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierPricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.BalancesTable,
			Columns: []string{modelcatalog.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbalance.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBalancesIDs(); len(nodes) > 0 && !_u.mutation.BalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.BalancesTable,
			Columns: []string{modelcatalog.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbalance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.BalancesTable,
			Columns: []string{modelcatalog.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbalance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModelCatalogUpdateOne is the builder for updating a single ModelCatalog entity.
type ModelCatalogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModelCatalogMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ModelCatalogUpdateOne) SetUpdatedAt(v time.Time) *ModelCatalogUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCanonicalName sets the "canonical_name" field.
func (_u *ModelCatalogUpdateOne) SetCanonicalName(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetCanonicalName(v)
	return _u
}

// SetNillableCanonicalName sets the "canonical_name" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableCanonicalName(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetCanonicalName(*v)
	}
	return _u
}

// SetPublicName sets the "public_name" field.
func (_u *ModelCatalogUpdateOne) SetPublicName(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetPublicName(v)
	return _u
}

// SetNillablePublicName sets the "public_name" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillablePublicName(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetPublicName(*v)
	}
	return _u
}

// SetContextWindow sets the "context_window" field.
func (_u *ModelCatalogUpdateOne) SetContextWindow(v int64) *ModelCatalogUpdateOne {
	_u.mutation.ResetContextWindow()
	_u.mutation.SetContextWindow(v)
	return _u
}

// SetNillableContextWindow sets the "context_window" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableContextWindow(v *int64) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetContextWindow(*v)
	}
	return _u
}

// AddContextWindow adds value to the "context_window" field.
func (_u *ModelCatalogUpdateOne) AddContextWindow(v int64) *ModelCatalogUpdateOne {
	_u.mutation.AddContextWindow(v)
	return _u
}

// ClearContextWindow clears the value of the "context_window" field.
func (_u *ModelCatalogUpdateOne) ClearContextWindow() *ModelCatalogUpdateOne {
	_u.mutation.ClearContextWindow()
	return _u
}

// SetSourceSuppliers sets the "source_suppliers" field.
func (_u *ModelCatalogUpdateOne) SetSourceSuppliers(v []string) *ModelCatalogUpdateOne {
	_u.mutation.SetSourceSuppliers(v)
	return _u
}

// AppendSourceSuppliers appends value to the "source_suppliers" field.
func (_u *ModelCatalogUpdateOne) AppendSourceSuppliers(v []string) *ModelCatalogUpdateOne {
	_u.mutation.AppendSourceSuppliers(v)
	return _u
}

// ClearSourceSuppliers clears the value of the "source_suppliers" field.
func (_u *ModelCatalogUpdateOne) ClearSourceSuppliers() *ModelCatalogUpdateOne {
	_u.mutation.ClearSourceSuppliers()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ModelCatalogUpdateOne) SetStatus(v string) *ModelCatalogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ModelCatalogUpdateOne) SetNillableStatus(v *string) *ModelCatalogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddPricingIDs adds the "pricing" edge to the ModelPricing entity by IDs.
func (_u *ModelCatalogUpdateOne) AddPricingIDs(ids ...string) *ModelCatalogUpdateOne {
	_u.mutation.AddPricingIDs(ids...)
	return _u
}

// AddPricing adds the "pricing" edges to the ModelPricing entity.
func (_u *ModelCatalogUpdateOne) AddPricing(v ...*ModelPricing) *ModelCatalogUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddPricingIDs(ids...)
}

// AddSupplierPricingIDs adds the "supplier_pricing" edge to the SupplierPricing entity by IDs.
func (_u *ModelCatalogUpdateOne) AddSupplierPricingIDs(ids ...string) *ModelCatalogUpdateOne {
	_u.mutation.AddSupplierPricingIDs(ids...)
	return _u
}

// AddSupplierPricing adds the "supplier_pricing" edges to the SupplierPricing entity.
func (_u *ModelCatalogUpdateOne) AddSupplierPricing(v ...*SupplierPricing) *ModelCatalogUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSupplierPricingIDs(ids...)
}

// AddBalanceIDs adds the "balances" edge to the ModelBalance entity by IDs.
func (_u *ModelCatalogUpdateOne) AddBalanceIDs(ids ...string) *ModelCatalogUpdateOne {
	_u.mutation.AddBalanceIDs(ids...)
	return _u
}

// AddBalances adds the "balances" edges to the ModelBalance entity.
func (_u *ModelCatalogUpdateOne) AddBalances(v ...*ModelBalance) *ModelCatalogUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBalanceIDs(ids...)
}

// Mutation returns the ModelCatalogMutation object of the builder.
func (_u *ModelCatalogUpdateOne) Mutation() *ModelCatalogMutation {
	return _u.mutation
}

// ClearPricing clears all "pricing" edges to the ModelPricing entity.
func (_u *ModelCatalogUpdateOne) ClearPricing() *ModelCatalogUpdateOne {
	_u.mutation.ClearPricing()
	return _u
}

// RemovePricingIDs removes the "pricing" edge to ModelPricing entities by IDs.
func (_u *ModelCatalogUpdateOne) RemovePricingIDs(ids ...string) *ModelCatalogUpdateOne {
	_u.mutation.RemovePricingIDs(ids...)
	return _u
}

// RemovePricing removes "pricing" edges to ModelPricing entities.
func (_u *ModelCatalogUpdateOne) RemovePricing(v ...*ModelPricing) *ModelCatalogUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemovePricingIDs(ids...)
}

// ClearSupplierPricing clears all "supplier_pricing" edges to the SupplierPricing entity.
func (_u *ModelCatalogUpdateOne) ClearSupplierPricing() *ModelCatalogUpdateOne {
	_u.mutation.ClearSupplierPricing()
	return _u
}

// RemoveSupplierPricingIDs removes the "supplier_pricing" edge to SupplierPricing entities by IDs.
func (_u *ModelCatalogUpdateOne) RemoveSupplierPricingIDs(ids ...string) *ModelCatalogUpdateOne {
	_u.mutation.RemoveSupplierPricingIDs(ids...)
	return _u
}

// RemoveSupplierPricing removes "supplier_pricing" edges to SupplierPricing entities.
func (_u *ModelCatalogUpdateOne) RemoveSupplierPricing(v ...*SupplierPricing) *ModelCatalogUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSupplierPricingIDs(ids...)
}

// ClearBalances clears all "balances" edges to the ModelBalance entity.
func (_u *ModelCatalogUpdateOne) ClearBalances() *ModelCatalogUpdateOne {
	_u.mutation.ClearBalances()
	return _u
}

// RemoveBalanceIDs removes the "balances" edge to ModelBalance entities by IDs.
func (_u *ModelCatalogUpdateOne) RemoveBalanceIDs(ids ...string) *ModelCatalogUpdateOne {
	_u.mutation.RemoveBalanceIDs(ids...)
	return _u
}

// RemoveBalances removes "balances" edges to ModelBalance entities.
func (_u *ModelCatalogUpdateOne) RemoveBalances(v ...*ModelBalance) *ModelCatalogUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBalanceIDs(ids...)
}

// Where appends a list predicates to the ModelCatalogUpdate builder.
func (_u *ModelCatalogUpdateOne) Where(ps ...predicate.ModelCatalog) *ModelCatalogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModelCatalogUpdateOne) Select(field string, fields ...string) *ModelCatalogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModelCatalog entity.
func (_u *ModelCatalogUpdateOne) Save(ctx context.Context) (*ModelCatalog, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModelCatalogUpdateOne) SaveX(ctx context.Context) *ModelCatalog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModelCatalogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModelCatalogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ModelCatalogUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := modelcatalog.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModelCatalogUpdateOne) check() error {
	if v, ok := _u.mutation.CanonicalName(); ok {
		if err := modelcatalog.CanonicalNameValidator(v); err != nil {
			return &ValidationError{Name: "canonical_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.canonical_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PublicName(); ok {
		if err := modelcatalog.PublicNameValidator(v); err != nil {
			return &ValidationError{Name: "public_name", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.public_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := modelcatalog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ModelCatalog.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ModelCatalogUpdateOne) sqlSave(ctx context.Context) (_node *ModelCatalog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(modelcatalog.Table, modelcatalog.Columns, sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModelCatalog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, modelcatalog.FieldID)
		for _, f := range fields {
			if !modelcatalog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != modelcatalog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(modelcatalog.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CanonicalName(); ok {
		_spec.SetField(modelcatalog.FieldCanonicalName, field.TypeString, value)
	}
	if value, ok := _u.mutation.PublicName(); ok {
		_spec.SetField(modelcatalog.FieldPublicName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContextWindow(); ok {
		_spec.SetField(modelcatalog.FieldContextWindow, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedContextWindow(); ok {
		_spec.AddField(modelcatalog.FieldContextWindow, field.TypeInt64, value)
	}
	if _u.mutation.ContextWindowCleared() {
		_spec.ClearField(modelcatalog.FieldContextWindow, field.TypeInt64)
	}
	if value, ok := _u.mutation.SourceSuppliers(); ok {
		_spec.SetField(modelcatalog.FieldSourceSuppliers, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSourceSuppliers(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, modelcatalog.FieldSourceSuppliers, value)
		})
	}
	if _u.mutation.SourceSuppliersCleared() {
		_spec.ClearField(modelcatalog.FieldSourceSuppliers, field.TypeJSON)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(modelcatalog.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.PricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedPricingIDs(); len(nodes) > 0 && !_u.mutation.PricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.PricingTable,
			Columns: []string{modelcatalog.PricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SupplierPricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSupplierPricingIDs(); len(nodes) > 0 && !_u.mutation.SupplierPricingCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SupplierPricingIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.SupplierPricingTable,
			Columns: []string{modelcatalog.SupplierPricingColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.BalancesTable,
			Columns: []string{modelcatalog.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbalance.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBalancesIDs(); len(nodes) > 0 && !_u.mutation.BalancesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.BalancesTable,
			Columns: []string{modelcatalog.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbalance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BalancesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   modelcatalog.BalancesTable,
			Columns: []string{modelcatalog.BalancesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelbalance.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModelCatalog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{modelcatalog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
