// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/qrispayment"
)

// QrisPayment is the model entity for the QrisPayment schema.
type QrisPayment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// AmountIdr holds the value of the "amount_idr" field.
	AmountIdr int64 `json:"amount_idr,omitempty"`
	// PaymentRef holds the value of the "payment_ref" field.
	PaymentRef string `json:"payment_ref,omitempty"`
	// QrString holds the value of the "qr_string" field.
	QrString string `json:"qr_string,omitempty"`
	// ImageBase64 holds the value of the "image_base64" field.
	ImageBase64 string `json:"image_base64,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// GomerchPayload holds the value of the "gomerch_payload" field.
	GomerchPayload map[string]interface{} `json:"gomerch_payload,omitempty"`
	// IdempotencyKey holds the value of the "idempotency_key" field.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the QrisPaymentQuery when eager-loading is set.
	Edges        QrisPaymentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// QrisPaymentEdges holds the relations/edges for other nodes in the graph.
type QrisPaymentEdges struct {
	// PaymentOrders holds the value of the payment_orders edge.
	PaymentOrders []*PaymentOrder `json:"payment_orders,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PaymentOrdersOrErr returns the PaymentOrders value or an error if the edge
// was not loaded in eager-loading.
func (e QrisPaymentEdges) PaymentOrdersOrErr() ([]*PaymentOrder, error) {
	if e.loadedTypes[0] {
		return e.PaymentOrders, nil
	}
	return nil, &NotLoadedError{edge: "payment_orders"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QrisPayment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case qrispayment.FieldGomerchPayload:
			values[i] = new([]byte)
		case qrispayment.FieldUserID, qrispayment.FieldAmountIdr:
			values[i] = new(sql.NullInt64)
		case qrispayment.FieldID, qrispayment.FieldPaymentRef, qrispayment.FieldQrString, qrispayment.FieldImageBase64, qrispayment.FieldStatus, qrispayment.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case qrispayment.FieldExpiresAt, qrispayment.FieldCreatedAt, qrispayment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QrisPayment fields.
func (_m *QrisPayment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case qrispayment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case qrispayment.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case qrispayment.FieldAmountIdr:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount_idr", values[i])
			} else if value.Valid {
				_m.AmountIdr = value.Int64
			}
		case qrispayment.FieldPaymentRef:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field payment_ref", values[i])
			} else if value.Valid {
				_m.PaymentRef = value.String
			}
		case qrispayment.FieldQrString:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field qr_string", values[i])
			} else if value.Valid {
				_m.QrString = value.String
			}
		case qrispayment.FieldImageBase64:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image_base64", values[i])
			} else if value.Valid {
				_m.ImageBase64 = value.String
			}
		case qrispayment.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case qrispayment.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case qrispayment.FieldGomerchPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field gomerch_payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.GomerchPayload); err != nil {
					return fmt.Errorf("unmarshal field gomerch_payload: %w", err)
				}
			}
		case qrispayment.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = new(string)
				*_m.IdempotencyKey = value.String
			}
		case qrispayment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case qrispayment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QrisPayment.
// This includes values selected through modifiers, order, etc.
func (_m *QrisPayment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPaymentOrders queries the "payment_orders" edge of the QrisPayment entity.
func (_m *QrisPayment) QueryPaymentOrders() *PaymentOrderQuery {
	return NewQrisPaymentClient(_m.config).QueryPaymentOrders(_m)
}

// Update returns a builder for updating this QrisPayment.
// Note that you need to call QrisPayment.Unwrap() before calling this method if this QrisPayment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QrisPayment) Update() *QrisPaymentUpdateOne {
	return NewQrisPaymentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QrisPayment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QrisPayment) Unwrap() *QrisPayment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QrisPayment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QrisPayment) String() string {
	var builder strings.Builder
	builder.WriteString("QrisPayment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("amount_idr=")
	builder.WriteString(fmt.Sprintf("%v", _m.AmountIdr))
	builder.WriteString(", ")
	builder.WriteString("payment_ref=")
	builder.WriteString(_m.PaymentRef)
	builder.WriteString(", ")
	builder.WriteString("qr_string=")
	builder.WriteString(_m.QrString)
	builder.WriteString(", ")
	builder.WriteString("image_base64=")
	builder.WriteString(_m.ImageBase64)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("gomerch_payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.GomerchPayload))
	builder.WriteString(", ")
	if v := _m.IdempotencyKey; v != nil {
		builder.WriteString("idempotency_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QrisPayments is a parsable slice of QrisPayment.
type QrisPayments []*QrisPayment
