// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/qrispayment"
)

// QrisPaymentCreate is the builder for creating a QrisPayment entity.
type QrisPaymentCreate struct {
	config
	mutation *QrisPaymentMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *QrisPaymentCreate) SetUserID(v int64) *QrisPaymentCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetAmountIdr sets the "amount_idr" field.
func (_c *QrisPaymentCreate) SetAmountIdr(v int64) *QrisPaymentCreate {
	_c.mutation.SetAmountIdr(v)
	return _c
}

// SetPaymentRef sets the "payment_ref" field.
func (_c *QrisPaymentCreate) SetPaymentRef(v string) *QrisPaymentCreate {
	_c.mutation.SetPaymentRef(v)
	return _c
}

// SetQrString sets the "qr_string" field.
func (_c *QrisPaymentCreate) SetQrString(v string) *QrisPaymentCreate {
	_c.mutation.SetQrString(v)
	return _c
}

// SetImageBase64 sets the "image_base64" field.
func (_c *QrisPaymentCreate) SetImageBase64(v string) *QrisPaymentCreate {
	_c.mutation.SetImageBase64(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *QrisPaymentCreate) SetExpiresAt(v time.Time) *QrisPaymentCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *QrisPaymentCreate) SetStatus(v string) *QrisPaymentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *QrisPaymentCreate) SetNillableStatus(v *string) *QrisPaymentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetGomerchPayload sets the "gomerch_payload" field.
func (_c *QrisPaymentCreate) SetGomerchPayload(v map[string]interface{}) *QrisPaymentCreate {
	_c.mutation.SetGomerchPayload(v)
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *QrisPaymentCreate) SetIdempotencyKey(v string) *QrisPaymentCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *QrisPaymentCreate) SetNillableIdempotencyKey(v *string) *QrisPaymentCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *QrisPaymentCreate) SetCreatedAt(v time.Time) *QrisPaymentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *QrisPaymentCreate) SetNillableCreatedAt(v *time.Time) *QrisPaymentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *QrisPaymentCreate) SetUpdatedAt(v time.Time) *QrisPaymentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *QrisPaymentCreate) SetNillableUpdatedAt(v *time.Time) *QrisPaymentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *QrisPaymentCreate) SetID(v string) *QrisPaymentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *QrisPaymentCreate) SetNillableID(v *string) *QrisPaymentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddPaymentOrderIDs adds the "payment_orders" edge to the PaymentOrder entity by IDs.
func (_c *QrisPaymentCreate) AddPaymentOrderIDs(ids ...int64) *QrisPaymentCreate {
	_c.mutation.AddPaymentOrderIDs(ids...)
	return _c
}

// AddPaymentOrders adds the "payment_orders" edges to the PaymentOrder entity.
func (_c *QrisPaymentCreate) AddPaymentOrders(v ...*PaymentOrder) *QrisPaymentCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPaymentOrderIDs(ids...)
}

// Mutation returns the QrisPaymentMutation object of the builder.
func (_c *QrisPaymentCreate) Mutation() *QrisPaymentMutation {
	return _c.mutation
}

// Save creates the QrisPayment in the database.
func (_c *QrisPaymentCreate) Save(ctx context.Context) (*QrisPayment, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *QrisPaymentCreate) SaveX(ctx context.Context) *QrisPayment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QrisPaymentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QrisPaymentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *QrisPaymentCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := qrispayment.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := qrispayment.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := qrispayment.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := qrispayment.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *QrisPaymentCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "QrisPayment.user_id"`)}
	}
	if _, ok := _c.mutation.AmountIdr(); !ok {
		return &ValidationError{Name: "amount_idr", err: errors.New(`ent: missing required field "QrisPayment.amount_idr"`)}
	}
	if _, ok := _c.mutation.PaymentRef(); !ok {
		return &ValidationError{Name: "payment_ref", err: errors.New(`ent: missing required field "QrisPayment.payment_ref"`)}
	}
	if v, ok := _c.mutation.PaymentRef(); ok {
		if err := qrispayment.PaymentRefValidator(v); err != nil {
			return &ValidationError{Name: "payment_ref", err: fmt.Errorf(`ent: validator failed for field "QrisPayment.payment_ref": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QrString(); !ok {
		return &ValidationError{Name: "qr_string", err: errors.New(`ent: missing required field "QrisPayment.qr_string"`)}
	}
	if _, ok := _c.mutation.ImageBase64(); !ok {
		return &ValidationError{Name: "image_base64", err: errors.New(`ent: missing required field "QrisPayment.image_base64"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "QrisPayment.expires_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "QrisPayment.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := qrispayment.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "QrisPayment.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := qrispayment.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "QrisPayment.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "QrisPayment.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "QrisPayment.updated_at"`)}
	}
	return nil
}

func (_c *QrisPaymentCreate) sqlSave(ctx context.Context) (*QrisPayment, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected QrisPayment.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *QrisPaymentCreate) createSpec() (*QrisPayment, *sqlgraph.CreateSpec) {
	var (
		_node = &QrisPayment{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(qrispayment.Table, sqlgraph.NewFieldSpec(qrispayment.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(qrispayment.FieldUserID, field.TypeInt64, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.AmountIdr(); ok {
		_spec.SetField(qrispayment.FieldAmountIdr, field.TypeInt64, value)
		_node.AmountIdr = value
	}
	if value, ok := _c.mutation.PaymentRef(); ok {
		_spec.SetField(qrispayment.FieldPaymentRef, field.TypeString, value)
		_node.PaymentRef = value
	}
	if value, ok := _c.mutation.QrString(); ok {
		_spec.SetField(qrispayment.FieldQrString, field.TypeString, value)
		_node.QrString = value
	}
	if value, ok := _c.mutation.ImageBase64(); ok {
		_spec.SetField(qrispayment.FieldImageBase64, field.TypeString, value)
		_node.ImageBase64 = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(qrispayment.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(qrispayment.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.GomerchPayload(); ok {
		_spec.SetField(qrispayment.FieldGomerchPayload, field.TypeJSON, value)
		_node.GomerchPayload = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(qrispayment.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(qrispayment.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(qrispayment.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.PaymentOrdersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   qrispayment.PaymentOrdersTable,
			Columns: []string{qrispayment.PaymentOrdersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QrisPayment.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QrisPaymentUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *QrisPaymentCreate) OnConflict(opts ...sql.ConflictOption) *QrisPaymentUpsertOne {
	_c.conflict = opts
	return &QrisPaymentUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QrisPayment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QrisPaymentCreate) OnConflictColumns(columns ...string) *QrisPaymentUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QrisPaymentUpsertOne{
		create: _c,
	}
}

type (
	// QrisPaymentUpsertOne is the builder for "upsert"-ing
	//  one QrisPayment node.
	QrisPaymentUpsertOne struct {
		create *QrisPaymentCreate
	}

	// QrisPaymentUpsert is the "OnConflict" setter.
	QrisPaymentUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *QrisPaymentUpsert) SetUserID(v int64) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateUserID() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldUserID)
	return u
}

// AddUserID adds v to the "user_id" field.
func (u *QrisPaymentUpsert) AddUserID(v int64) *QrisPaymentUpsert {
	u.Add(qrispayment.FieldUserID, v)
	return u
}

// SetAmountIdr sets the "amount_idr" field.
func (u *QrisPaymentUpsert) SetAmountIdr(v int64) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldAmountIdr, v)
	return u
}

// UpdateAmountIdr sets the "amount_idr" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateAmountIdr() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldAmountIdr)
	return u
}

// AddAmountIdr adds v to the "amount_idr" field.
func (u *QrisPaymentUpsert) AddAmountIdr(v int64) *QrisPaymentUpsert {
	u.Add(qrispayment.FieldAmountIdr, v)
	return u
}

// SetPaymentRef sets the "payment_ref" field.
func (u *QrisPaymentUpsert) SetPaymentRef(v string) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldPaymentRef, v)
	return u
}

// UpdatePaymentRef sets the "payment_ref" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdatePaymentRef() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldPaymentRef)
	return u
}

// SetQrString sets the "qr_string" field.
func (u *QrisPaymentUpsert) SetQrString(v string) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldQrString, v)
	return u
}

// UpdateQrString sets the "qr_string" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateQrString() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldQrString)
	return u
}

// SetImageBase64 sets the "image_base64" field.
func (u *QrisPaymentUpsert) SetImageBase64(v string) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldImageBase64, v)
	return u
}

// UpdateImageBase64 sets the "image_base64" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateImageBase64() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldImageBase64)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *QrisPaymentUpsert) SetExpiresAt(v time.Time) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateExpiresAt() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldExpiresAt)
	return u
}

// SetStatus sets the "status" field.
func (u *QrisPaymentUpsert) SetStatus(v string) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateStatus() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldStatus)
	return u
}

// SetGomerchPayload sets the "gomerch_payload" field.
func (u *QrisPaymentUpsert) SetGomerchPayload(v map[string]interface{}) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldGomerchPayload, v)
	return u
}

// UpdateGomerchPayload sets the "gomerch_payload" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateGomerchPayload() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldGomerchPayload)
	return u
}

// ClearGomerchPayload clears the value of the "gomerch_payload" field.
func (u *QrisPaymentUpsert) ClearGomerchPayload() *QrisPaymentUpsert {
	u.SetNull(qrispayment.FieldGomerchPayload)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *QrisPaymentUpsert) SetIdempotencyKey(v string) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateIdempotencyKey() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *QrisPaymentUpsert) ClearIdempotencyKey() *QrisPaymentUpsert {
	u.SetNull(qrispayment.FieldIdempotencyKey)
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *QrisPaymentUpsert) SetCreatedAt(v time.Time) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateCreatedAt() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QrisPaymentUpsert) SetUpdatedAt(v time.Time) *QrisPaymentUpsert {
	u.Set(qrispayment.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QrisPaymentUpsert) UpdateUpdatedAt() *QrisPaymentUpsert {
	u.SetExcluded(qrispayment.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.QrisPayment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(qrispayment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QrisPaymentUpsertOne) UpdateNewValues() *QrisPaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(qrispayment.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QrisPayment.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *QrisPaymentUpsertOne) Ignore() *QrisPaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QrisPaymentUpsertOne) DoNothing() *QrisPaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QrisPaymentCreate.OnConflict
// documentation for more info.
func (u *QrisPaymentUpsertOne) Update(set func(*QrisPaymentUpsert)) *QrisPaymentUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QrisPaymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *QrisPaymentUpsertOne) SetUserID(v int64) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *QrisPaymentUpsertOne) AddUserID(v int64) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateUserID() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateUserID()
	})
}

// SetAmountIdr sets the "amount_idr" field.
func (u *QrisPaymentUpsertOne) SetAmountIdr(v int64) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetAmountIdr(v)
	})
}

// AddAmountIdr adds v to the "amount_idr" field.
func (u *QrisPaymentUpsertOne) AddAmountIdr(v int64) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.AddAmountIdr(v)
	})
}

// UpdateAmountIdr sets the "amount_idr" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateAmountIdr() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateAmountIdr()
	})
}

// SetPaymentRef sets the "payment_ref" field.
func (u *QrisPaymentUpsertOne) SetPaymentRef(v string) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetPaymentRef(v)
	})
}

// UpdatePaymentRef sets the "payment_ref" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdatePaymentRef() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdatePaymentRef()
	})
}

// SetQrString sets the "qr_string" field.
func (u *QrisPaymentUpsertOne) SetQrString(v string) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetQrString(v)
	})
}

// UpdateQrString sets the "qr_string" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateQrString() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateQrString()
	})
}

// SetImageBase64 sets the "image_base64" field.
func (u *QrisPaymentUpsertOne) SetImageBase64(v string) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetImageBase64(v)
	})
}

// UpdateImageBase64 sets the "image_base64" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateImageBase64() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateImageBase64()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *QrisPaymentUpsertOne) SetExpiresAt(v time.Time) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateExpiresAt() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *QrisPaymentUpsertOne) SetStatus(v string) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateStatus() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateStatus()
	})
}

// SetGomerchPayload sets the "gomerch_payload" field.
func (u *QrisPaymentUpsertOne) SetGomerchPayload(v map[string]interface{}) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetGomerchPayload(v)
	})
}

// UpdateGomerchPayload sets the "gomerch_payload" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateGomerchPayload() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateGomerchPayload()
	})
}

// ClearGomerchPayload clears the value of the "gomerch_payload" field.
func (u *QrisPaymentUpsertOne) ClearGomerchPayload() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.ClearGomerchPayload()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *QrisPaymentUpsertOne) SetIdempotencyKey(v string) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateIdempotencyKey() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *QrisPaymentUpsertOne) ClearIdempotencyKey() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *QrisPaymentUpsertOne) SetCreatedAt(v time.Time) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateCreatedAt() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QrisPaymentUpsertOne) SetUpdatedAt(v time.Time) *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QrisPaymentUpsertOne) UpdateUpdatedAt() *QrisPaymentUpsertOne {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *QrisPaymentUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QrisPaymentCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QrisPaymentUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *QrisPaymentUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: QrisPaymentUpsertOne.ID is not supported by MySQL driver. Use QrisPaymentUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *QrisPaymentUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// QrisPaymentCreateBulk is the builder for creating many QrisPayment entities in bulk.
type QrisPaymentCreateBulk struct {
	config
	err      error
	builders []*QrisPaymentCreate
	conflict []sql.ConflictOption
}

// Save creates the QrisPayment entities in the database.
func (_c *QrisPaymentCreateBulk) Save(ctx context.Context) ([]*QrisPayment, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*QrisPayment, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*QrisPaymentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *QrisPaymentCreateBulk) SaveX(ctx context.Context) []*QrisPayment {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *QrisPaymentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *QrisPaymentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.QrisPayment.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.QrisPaymentUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *QrisPaymentCreateBulk) OnConflict(opts ...sql.ConflictOption) *QrisPaymentUpsertBulk {
	_c.conflict = opts
	return &QrisPaymentUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.QrisPayment.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *QrisPaymentCreateBulk) OnConflictColumns(columns ...string) *QrisPaymentUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &QrisPaymentUpsertBulk{
		create: _c,
	}
}

// QrisPaymentUpsertBulk is the builder for "upsert"-ing
// a bulk of QrisPayment nodes.
type QrisPaymentUpsertBulk struct {
	create *QrisPaymentCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.QrisPayment.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(qrispayment.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *QrisPaymentUpsertBulk) UpdateNewValues() *QrisPaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(qrispayment.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.QrisPayment.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *QrisPaymentUpsertBulk) Ignore() *QrisPaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *QrisPaymentUpsertBulk) DoNothing() *QrisPaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the QrisPaymentCreateBulk.OnConflict
// documentation for more info.
func (u *QrisPaymentUpsertBulk) Update(set func(*QrisPaymentUpsert)) *QrisPaymentUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&QrisPaymentUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *QrisPaymentUpsertBulk) SetUserID(v int64) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetUserID(v)
	})
}

// AddUserID adds v to the "user_id" field.
func (u *QrisPaymentUpsertBulk) AddUserID(v int64) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.AddUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateUserID() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateUserID()
	})
}

// SetAmountIdr sets the "amount_idr" field.
func (u *QrisPaymentUpsertBulk) SetAmountIdr(v int64) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetAmountIdr(v)
	})
}

// AddAmountIdr adds v to the "amount_idr" field.
func (u *QrisPaymentUpsertBulk) AddAmountIdr(v int64) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.AddAmountIdr(v)
	})
}

// UpdateAmountIdr sets the "amount_idr" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateAmountIdr() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateAmountIdr()
	})
}

// SetPaymentRef sets the "payment_ref" field.
func (u *QrisPaymentUpsertBulk) SetPaymentRef(v string) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetPaymentRef(v)
	})
}

// UpdatePaymentRef sets the "payment_ref" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdatePaymentRef() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdatePaymentRef()
	})
}

// SetQrString sets the "qr_string" field.
func (u *QrisPaymentUpsertBulk) SetQrString(v string) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetQrString(v)
	})
}

// UpdateQrString sets the "qr_string" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateQrString() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateQrString()
	})
}

// SetImageBase64 sets the "image_base64" field.
func (u *QrisPaymentUpsertBulk) SetImageBase64(v string) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetImageBase64(v)
	})
}

// UpdateImageBase64 sets the "image_base64" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateImageBase64() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateImageBase64()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *QrisPaymentUpsertBulk) SetExpiresAt(v time.Time) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateExpiresAt() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetStatus sets the "status" field.
func (u *QrisPaymentUpsertBulk) SetStatus(v string) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateStatus() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateStatus()
	})
}

// SetGomerchPayload sets the "gomerch_payload" field.
func (u *QrisPaymentUpsertBulk) SetGomerchPayload(v map[string]interface{}) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetGomerchPayload(v)
	})
}

// UpdateGomerchPayload sets the "gomerch_payload" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateGomerchPayload() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateGomerchPayload()
	})
}

// ClearGomerchPayload clears the value of the "gomerch_payload" field.
func (u *QrisPaymentUpsertBulk) ClearGomerchPayload() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.ClearGomerchPayload()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *QrisPaymentUpsertBulk) SetIdempotencyKey(v string) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateIdempotencyKey() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *QrisPaymentUpsertBulk) ClearIdempotencyKey() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetCreatedAt sets the "created_at" field.
func (u *QrisPaymentUpsertBulk) SetCreatedAt(v time.Time) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateCreatedAt() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *QrisPaymentUpsertBulk) SetUpdatedAt(v time.Time) *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *QrisPaymentUpsertBulk) UpdateUpdatedAt() *QrisPaymentUpsertBulk {
	return u.Update(func(s *QrisPaymentUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *QrisPaymentUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the QrisPaymentCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for QrisPaymentCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *QrisPaymentUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
