// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/modelcatalog"
	"github.com/Wei-Shaw/sub2api/ent/supplierpricing"
)

// SupplierPricingCreate is the builder for creating a SupplierPricing entity.
type SupplierPricingCreate struct {
	config
	mutation *SupplierPricingMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetModelID sets the "model_id" field.
func (_c *SupplierPricingCreate) SetModelID(v string) *SupplierPricingCreate {
	_c.mutation.SetModelID(v)
	return _c
}

// SetNillableModelID sets the "model_id" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableModelID(v *string) *SupplierPricingCreate {
	if v != nil {
		_c.SetModelID(*v)
	}
	return _c
}

// SetSupplierCode sets the "supplier_code" field.
func (_c *SupplierPricingCreate) SetSupplierCode(v string) *SupplierPricingCreate {
	_c.mutation.SetSupplierCode(v)
	return _c
}

// SetVersion sets the "version" field.
func (_c *SupplierPricingCreate) SetVersion(v int) *SupplierPricingCreate {
	_c.mutation.SetVersion(v)
	return _c
}

// SetTierLabel sets the "tier_label" field.
func (_c *SupplierPricingCreate) SetTierLabel(v string) *SupplierPricingCreate {
	_c.mutation.SetTierLabel(v)
	return _c
}

// SetNillableTierLabel sets the "tier_label" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableTierLabel(v *string) *SupplierPricingCreate {
	if v != nil {
		_c.SetTierLabel(*v)
	}
	return _c
}

// SetAvailability sets the "availability" field.
func (_c *SupplierPricingCreate) SetAvailability(v string) *SupplierPricingCreate {
	_c.mutation.SetAvailability(v)
	return _c
}

// SetNillableAvailability sets the "availability" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableAvailability(v *string) *SupplierPricingCreate {
	if v != nil {
		_c.SetAvailability(*v)
	}
	return _c
}

// SetInputRate sets the "input_rate" field.
func (_c *SupplierPricingCreate) SetInputRate(v float64) *SupplierPricingCreate {
	_c.mutation.SetInputRate(v)
	return _c
}

// SetNillableInputRate sets the "input_rate" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableInputRate(v *float64) *SupplierPricingCreate {
	if v != nil {
		_c.SetInputRate(*v)
	}
	return _c
}

// SetOutputRate sets the "output_rate" field.
func (_c *SupplierPricingCreate) SetOutputRate(v float64) *SupplierPricingCreate {
	_c.mutation.SetOutputRate(v)
	return _c
}

// SetNillableOutputRate sets the "output_rate" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableOutputRate(v *float64) *SupplierPricingCreate {
	if v != nil {
		_c.SetOutputRate(*v)
	}
	return _c
}

// SetCachedReadRate sets the "cached_read_rate" field.
func (_c *SupplierPricingCreate) SetCachedReadRate(v float64) *SupplierPricingCreate {
	_c.mutation.SetCachedReadRate(v)
	return _c
}

// SetNillableCachedReadRate sets the "cached_read_rate" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableCachedReadRate(v *float64) *SupplierPricingCreate {
	if v != nil {
		_c.SetCachedReadRate(*v)
	}
	return _c
}

// SetCachedWriteRate sets the "cached_write_rate" field.
func (_c *SupplierPricingCreate) SetCachedWriteRate(v float64) *SupplierPricingCreate {
	_c.mutation.SetCachedWriteRate(v)
	return _c
}

// SetNillableCachedWriteRate sets the "cached_write_rate" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableCachedWriteRate(v *float64) *SupplierPricingCreate {
	if v != nil {
		_c.SetCachedWriteRate(*v)
	}
	return _c
}

// SetCacheCapabilities sets the "cache_capabilities" field.
func (_c *SupplierPricingCreate) SetCacheCapabilities(v map[string]bool) *SupplierPricingCreate {
	_c.mutation.SetCacheCapabilities(v)
	return _c
}

// SetEffectiveFrom sets the "effective_from" field.
func (_c *SupplierPricingCreate) SetEffectiveFrom(v time.Time) *SupplierPricingCreate {
	_c.mutation.SetEffectiveFrom(v)
	return _c
}

// SetNillableEffectiveFrom sets the "effective_from" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableEffectiveFrom(v *time.Time) *SupplierPricingCreate {
	if v != nil {
		_c.SetEffectiveFrom(*v)
	}
	return _c
}

// SetEffectiveTo sets the "effective_to" field.
func (_c *SupplierPricingCreate) SetEffectiveTo(v time.Time) *SupplierPricingCreate {
	_c.mutation.SetEffectiveTo(v)
	return _c
}

// SetNillableEffectiveTo sets the "effective_to" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableEffectiveTo(v *time.Time) *SupplierPricingCreate {
	if v != nil {
		_c.SetEffectiveTo(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SupplierPricingCreate) SetID(v string) *SupplierPricingCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SupplierPricingCreate) SetNillableID(v *string) *SupplierPricingCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetModel sets the "model" edge to the ModelCatalog entity.
func (_c *SupplierPricingCreate) SetModel(v *ModelCatalog) *SupplierPricingCreate {
	return _c.SetModelID(v.ID)
}

// Mutation returns the SupplierPricingMutation object of the builder.
func (_c *SupplierPricingCreate) Mutation() *SupplierPricingMutation {
	return _c.mutation
}

// Save creates the SupplierPricing in the database.
func (_c *SupplierPricingCreate) Save(ctx context.Context) (*SupplierPricing, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupplierPricingCreate) SaveX(ctx context.Context) *SupplierPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierPricingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierPricingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupplierPricingCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := supplierpricing.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupplierPricingCreate) check() error {
	if _, ok := _c.mutation.SupplierCode(); !ok {
		return &ValidationError{Name: "supplier_code", err: errors.New(`ent: missing required field "SupplierPricing.supplier_code"`)}
	}
	if v, ok := _c.mutation.SupplierCode(); ok {
		if err := supplierpricing.SupplierCodeValidator(v); err != nil {
			return &ValidationError{Name: "supplier_code", err: fmt.Errorf(`ent: validator failed for field "SupplierPricing.supplier_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Version(); !ok {
		return &ValidationError{Name: "version", err: errors.New(`ent: missing required field "SupplierPricing.version"`)}
	}
	if v, ok := _c.mutation.TierLabel(); ok {
		if err := supplierpricing.TierLabelValidator(v); err != nil {
			return &ValidationError{Name: "tier_label", err: fmt.Errorf(`ent: validator failed for field "SupplierPricing.tier_label": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Availability(); ok {
		if err := supplierpricing.AvailabilityValidator(v); err != nil {
			return &ValidationError{Name: "availability", err: fmt.Errorf(`ent: validator failed for field "SupplierPricing.availability": %w`, err)}
		}
	}
	return nil
}

func (_c *SupplierPricingCreate) sqlSave(ctx context.Context) (*SupplierPricing, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SupplierPricing.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupplierPricingCreate) createSpec() (*SupplierPricing, *sqlgraph.CreateSpec) {
	var (
		_node = &SupplierPricing{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supplierpricing.Table, sqlgraph.NewFieldSpec(supplierpricing.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SupplierCode(); ok {
		_spec.SetField(supplierpricing.FieldSupplierCode, field.TypeString, value)
		_node.SupplierCode = value
	}
	if value, ok := _c.mutation.Version(); ok {
		_spec.SetField(supplierpricing.FieldVersion, field.TypeInt, value)
		_node.Version = value
	}
	if value, ok := _c.mutation.TierLabel(); ok {
		_spec.SetField(supplierpricing.FieldTierLabel, field.TypeString, value)
		_node.TierLabel = &value
	}
	if value, ok := _c.mutation.Availability(); ok {
		_spec.SetField(supplierpricing.FieldAvailability, field.TypeString, value)
		_node.Availability = &value
	}
	if value, ok := _c.mutation.InputRate(); ok {
		_spec.SetField(supplierpricing.FieldInputRate, field.TypeFloat64, value)
		_node.InputRate = &value
	}
	if value, ok := _c.mutation.OutputRate(); ok {
		_spec.SetField(supplierpricing.FieldOutputRate, field.TypeFloat64, value)
		_node.OutputRate = &value
	}
	if value, ok := _c.mutation.CachedReadRate(); ok {
		_spec.SetField(supplierpricing.FieldCachedReadRate, field.TypeFloat64, value)
		_node.CachedReadRate = &value
	}
	if value, ok := _c.mutation.CachedWriteRate(); ok {
		_spec.SetField(supplierpricing.FieldCachedWriteRate, field.TypeFloat64, value)
		_node.CachedWriteRate = &value
	}
	if value, ok := _c.mutation.CacheCapabilities(); ok {
		_spec.SetField(supplierpricing.FieldCacheCapabilities, field.TypeJSON, value)
		_node.CacheCapabilities = value
	}
	if value, ok := _c.mutation.EffectiveFrom(); ok {
		_spec.SetField(supplierpricing.FieldEffectiveFrom, field.TypeTime, value)
		_node.EffectiveFrom = &value
	}
	if value, ok := _c.mutation.EffectiveTo(); ok {
		_spec.SetField(supplierpricing.FieldEffectiveTo, field.TypeTime, value)
		_node.EffectiveTo = &value
	}
	if nodes := _c.mutation.ModelIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   supplierpricing.ModelTable,
			Columns: []string{supplierpricing.ModelColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(modelcatalog.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ModelID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierPricing.Create().
//		SetModelID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierPricingUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierPricingCreate) OnConflict(opts ...sql.ConflictOption) *SupplierPricingUpsertOne {
	_c.conflict = opts
	return &SupplierPricingUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierPricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierPricingCreate) OnConflictColumns(columns ...string) *SupplierPricingUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierPricingUpsertOne{
		create: _c,
	}
}

type (
	// SupplierPricingUpsertOne is the builder for "upsert"-ing
	//  one SupplierPricing node.
	SupplierPricingUpsertOne struct {
		create *SupplierPricingCreate
	}

	// SupplierPricingUpsert is the "OnConflict" setter.
	SupplierPricingUpsert struct {
		*sql.UpdateSet
	}
)

// SetModelID sets the "model_id" field.
func (u *SupplierPricingUpsert) SetModelID(v string) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldModelID, v)
	return u
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateModelID() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldModelID)
	return u
}

// ClearModelID clears the value of the "model_id" field.
func (u *SupplierPricingUpsert) ClearModelID() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldModelID)
	return u
}

// SetSupplierCode sets the "supplier_code" field.
func (u *SupplierPricingUpsert) SetSupplierCode(v string) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldSupplierCode, v)
	return u
}

// UpdateSupplierCode sets the "supplier_code" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateSupplierCode() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldSupplierCode)
	return u
}

// SetVersion sets the "version" field.
func (u *SupplierPricingUpsert) SetVersion(v int) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldVersion, v)
	return u
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateVersion() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldVersion)
	return u
}

// AddVersion adds v to the "version" field.
func (u *SupplierPricingUpsert) AddVersion(v int) *SupplierPricingUpsert {
	u.Add(supplierpricing.FieldVersion, v)
	return u
}

// SetTierLabel sets the "tier_label" field.
func (u *SupplierPricingUpsert) SetTierLabel(v string) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldTierLabel, v)
	return u
}

// UpdateTierLabel sets the "tier_label" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateTierLabel() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldTierLabel)
	return u
}

// ClearTierLabel clears the value of the "tier_label" field.
func (u *SupplierPricingUpsert) ClearTierLabel() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldTierLabel)
	return u
}

// SetAvailability sets the "availability" field.
func (u *SupplierPricingUpsert) SetAvailability(v string) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldAvailability, v)
	return u
}

// UpdateAvailability sets the "availability" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateAvailability() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldAvailability)
	return u
}

// ClearAvailability clears the value of the "availability" field.
func (u *SupplierPricingUpsert) ClearAvailability() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldAvailability)
	return u
}

// SetInputRate sets the "input_rate" field.
func (u *SupplierPricingUpsert) SetInputRate(v float64) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldInputRate, v)
	return u
}

// UpdateInputRate sets the "input_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateInputRate() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldInputRate)
	return u
}

// AddInputRate adds v to the "input_rate" field.
func (u *SupplierPricingUpsert) AddInputRate(v float64) *SupplierPricingUpsert {
	u.Add(supplierpricing.FieldInputRate, v)
	return u
}

// ClearInputRate clears the value of the "input_rate" field.
func (u *SupplierPricingUpsert) ClearInputRate() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldInputRate)
	return u
}

// SetOutputRate sets the "output_rate" field.
func (u *SupplierPricingUpsert) SetOutputRate(v float64) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldOutputRate, v)
	return u
}

// UpdateOutputRate sets the "output_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateOutputRate() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldOutputRate)
	return u
}

// AddOutputRate adds v to the "output_rate" field.
func (u *SupplierPricingUpsert) AddOutputRate(v float64) *SupplierPricingUpsert {
	u.Add(supplierpricing.FieldOutputRate, v)
	return u
}

// ClearOutputRate clears the value of the "output_rate" field.
func (u *SupplierPricingUpsert) ClearOutputRate() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldOutputRate)
	return u
}

// SetCachedReadRate sets the "cached_read_rate" field.
func (u *SupplierPricingUpsert) SetCachedReadRate(v float64) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldCachedReadRate, v)
	return u
}

// UpdateCachedReadRate sets the "cached_read_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateCachedReadRate() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldCachedReadRate)
	return u
}

// AddCachedReadRate adds v to the "cached_read_rate" field.
func (u *SupplierPricingUpsert) AddCachedReadRate(v float64) *SupplierPricingUpsert {
	u.Add(supplierpricing.FieldCachedReadRate, v)
	return u
}

// ClearCachedReadRate clears the value of the "cached_read_rate" field.
func (u *SupplierPricingUpsert) ClearCachedReadRate() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldCachedReadRate)
	return u
}

// SetCachedWriteRate sets the "cached_write_rate" field.
func (u *SupplierPricingUpsert) SetCachedWriteRate(v float64) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldCachedWriteRate, v)
	return u
}

// UpdateCachedWriteRate sets the "cached_write_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateCachedWriteRate() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldCachedWriteRate)
	return u
}

// AddCachedWriteRate adds v to the "cached_write_rate" field.
func (u *SupplierPricingUpsert) AddCachedWriteRate(v float64) *SupplierPricingUpsert {
	u.Add(supplierpricing.FieldCachedWriteRate, v)
	return u
}

// ClearCachedWriteRate clears the value of the "cached_write_rate" field.
func (u *SupplierPricingUpsert) ClearCachedWriteRate() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldCachedWriteRate)
	return u
}

// SetCacheCapabilities sets the "cache_capabilities" field.
func (u *SupplierPricingUpsert) SetCacheCapabilities(v map[string]bool) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldCacheCapabilities, v)
	return u
}

// UpdateCacheCapabilities sets the "cache_capabilities" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateCacheCapabilities() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldCacheCapabilities)
	return u
}

// ClearCacheCapabilities clears the value of the "cache_capabilities" field.
func (u *SupplierPricingUpsert) ClearCacheCapabilities() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldCacheCapabilities)
	return u
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *SupplierPricingUpsert) SetEffectiveFrom(v time.Time) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldEffectiveFrom, v)
	return u
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateEffectiveFrom() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldEffectiveFrom)
	return u
}

// ClearEffectiveFrom clears the value of the "effective_from" field.
func (u *SupplierPricingUpsert) ClearEffectiveFrom() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldEffectiveFrom)
	return u
}

// SetEffectiveTo sets the "effective_to" field.
func (u *SupplierPricingUpsert) SetEffectiveTo(v time.Time) *SupplierPricingUpsert {
	u.Set(supplierpricing.FieldEffectiveTo, v)
	return u
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *SupplierPricingUpsert) UpdateEffectiveTo() *SupplierPricingUpsert {
	u.SetExcluded(supplierpricing.FieldEffectiveTo)
	return u
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *SupplierPricingUpsert) ClearEffectiveTo() *SupplierPricingUpsert {
	u.SetNull(supplierpricing.FieldEffectiveTo)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SupplierPricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(supplierpricing.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SupplierPricingUpsertOne) UpdateNewValues() *SupplierPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(supplierpricing.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierPricing.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupplierPricingUpsertOne) Ignore() *SupplierPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierPricingUpsertOne) DoNothing() *SupplierPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierPricingCreate.OnConflict
// documentation for more info.
func (u *SupplierPricingUpsertOne) Update(set func(*SupplierPricingUpsert)) *SupplierPricingUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierPricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *SupplierPricingUpsertOne) SetModelID(v string) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateModelID() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateModelID()
	})
}

// ClearModelID clears the value of the "model_id" field.
func (u *SupplierPricingUpsertOne) ClearModelID() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearModelID()
	})
}

// SetSupplierCode sets the "supplier_code" field.
func (u *SupplierPricingUpsertOne) SetSupplierCode(v string) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetSupplierCode(v)
	})
}

// UpdateSupplierCode sets the "supplier_code" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateSupplierCode() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateSupplierCode()
	})
}

// SetVersion sets the "version" field.
func (u *SupplierPricingUpsertOne) SetVersion(v int) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SupplierPricingUpsertOne) AddVersion(v int) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateVersion() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateVersion()
	})
}

// SetTierLabel sets the "tier_label" field.
func (u *SupplierPricingUpsertOne) SetTierLabel(v string) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetTierLabel(v)
	})
}

// UpdateTierLabel sets the "tier_label" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateTierLabel() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateTierLabel()
	})
}

// ClearTierLabel clears the value of the "tier_label" field.
func (u *SupplierPricingUpsertOne) ClearTierLabel() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearTierLabel()
	})
}

// SetAvailability sets the "availability" field.
func (u *SupplierPricingUpsertOne) SetAvailability(v string) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetAvailability(v)
	})
}

// UpdateAvailability sets the "availability" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateAvailability() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateAvailability()
	})
}

// ClearAvailability clears the value of the "availability" field.
func (u *SupplierPricingUpsertOne) ClearAvailability() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearAvailability()
	})
}

// SetInputRate sets the "input_rate" field.
func (u *SupplierPricingUpsertOne) SetInputRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetInputRate(v)
	})
}

// AddInputRate adds v to the "input_rate" field.
func (u *SupplierPricingUpsertOne) AddInputRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddInputRate(v)
	})
}

// UpdateInputRate sets the "input_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateInputRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateInputRate()
	})
}

// ClearInputRate clears the value of the "input_rate" field.
func (u *SupplierPricingUpsertOne) ClearInputRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearInputRate()
	})
}

// SetOutputRate sets the "output_rate" field.
func (u *SupplierPricingUpsertOne) SetOutputRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetOutputRate(v)
	})
}

// AddOutputRate adds v to the "output_rate" field.
func (u *SupplierPricingUpsertOne) AddOutputRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddOutputRate(v)
	})
}

// UpdateOutputRate sets the "output_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateOutputRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateOutputRate()
	})
}

// ClearOutputRate clears the value of the "output_rate" field.
func (u *SupplierPricingUpsertOne) ClearOutputRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearOutputRate()
	})
}

// SetCachedReadRate sets the "cached_read_rate" field.
func (u *SupplierPricingUpsertOne) SetCachedReadRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetCachedReadRate(v)
	})
}

// AddCachedReadRate adds v to the "cached_read_rate" field.
func (u *SupplierPricingUpsertOne) AddCachedReadRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddCachedReadRate(v)
	})
}

// UpdateCachedReadRate sets the "cached_read_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateCachedReadRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateCachedReadRate()
	})
}

// ClearCachedReadRate clears the value of the "cached_read_rate" field.
func (u *SupplierPricingUpsertOne) ClearCachedReadRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearCachedReadRate()
	})
}

// SetCachedWriteRate sets the "cached_write_rate" field.
func (u *SupplierPricingUpsertOne) SetCachedWriteRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetCachedWriteRate(v)
	})
}

// AddCachedWriteRate adds v to the "cached_write_rate" field.
func (u *SupplierPricingUpsertOne) AddCachedWriteRate(v float64) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddCachedWriteRate(v)
	})
}

// UpdateCachedWriteRate sets the "cached_write_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateCachedWriteRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateCachedWriteRate()
	})
}

// ClearCachedWriteRate clears the value of the "cached_write_rate" field.
func (u *SupplierPricingUpsertOne) ClearCachedWriteRate() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearCachedWriteRate()
	})
}

// SetCacheCapabilities sets the "cache_capabilities" field.
func (u *SupplierPricingUpsertOne) SetCacheCapabilities(v map[string]bool) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetCacheCapabilities(v)
	})
}

// UpdateCacheCapabilities sets the "cache_capabilities" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateCacheCapabilities() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateCacheCapabilities()
	})
}

// ClearCacheCapabilities clears the value of the "cache_capabilities" field.
func (u *SupplierPricingUpsertOne) ClearCacheCapabilities() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearCacheCapabilities()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *SupplierPricingUpsertOne) SetEffectiveFrom(v time.Time) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateEffectiveFrom() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// ClearEffectiveFrom clears the value of the "effective_from" field.
func (u *SupplierPricingUpsertOne) ClearEffectiveFrom() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearEffectiveFrom()
	})
}

// SetEffectiveTo sets the "effective_to" field.
func (u *SupplierPricingUpsertOne) SetEffectiveTo(v time.Time) *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetEffectiveTo(v)
	})
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *SupplierPricingUpsertOne) UpdateEffectiveTo() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateEffectiveTo()
	})
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *SupplierPricingUpsertOne) ClearEffectiveTo() *SupplierPricingUpsertOne {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearEffectiveTo()
	})
}

// Exec executes the query.
func (u *SupplierPricingUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierPricingCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierPricingUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupplierPricingUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SupplierPricingUpsertOne.ID is not supported by MySQL driver. Use SupplierPricingUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupplierPricingUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupplierPricingCreateBulk is the builder for creating many SupplierPricing entities in bulk.
type SupplierPricingCreateBulk struct {
	config
	err      error
	builders []*SupplierPricingCreate
	conflict []sql.ConflictOption
}

// Save creates the SupplierPricing entities in the database.
func (_c *SupplierPricingCreateBulk) Save(ctx context.Context) ([]*SupplierPricing, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupplierPricing, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierPricingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupplierPricingCreateBulk) SaveX(ctx context.Context) []*SupplierPricing {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierPricingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierPricingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierPricing.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierPricingUpsert) {
//			SetModelID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierPricingCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupplierPricingUpsertBulk {
	_c.conflict = opts
	return &SupplierPricingUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierPricing.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierPricingCreateBulk) OnConflictColumns(columns ...string) *SupplierPricingUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierPricingUpsertBulk{
		create: _c,
	}
}

// SupplierPricingUpsertBulk is the builder for "upsert"-ing
// a bulk of SupplierPricing nodes.
type SupplierPricingUpsertBulk struct {
	create *SupplierPricingCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupplierPricing.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(supplierpricing.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SupplierPricingUpsertBulk) UpdateNewValues() *SupplierPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(supplierpricing.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierPricing.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupplierPricingUpsertBulk) Ignore() *SupplierPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierPricingUpsertBulk) DoNothing() *SupplierPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierPricingCreateBulk.OnConflict
// documentation for more info.
func (u *SupplierPricingUpsertBulk) Update(set func(*SupplierPricingUpsert)) *SupplierPricingUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierPricingUpsert{UpdateSet: update})
	}))
	return u
}

// SetModelID sets the "model_id" field.
func (u *SupplierPricingUpsertBulk) SetModelID(v string) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetModelID(v)
	})
}

// UpdateModelID sets the "model_id" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateModelID() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateModelID()
	})
}

// ClearModelID clears the value of the "model_id" field.
func (u *SupplierPricingUpsertBulk) ClearModelID() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearModelID()
	})
}

// SetSupplierCode sets the "supplier_code" field.
func (u *SupplierPricingUpsertBulk) SetSupplierCode(v string) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetSupplierCode(v)
	})
}

// UpdateSupplierCode sets the "supplier_code" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateSupplierCode() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateSupplierCode()
	})
}

// SetVersion sets the "version" field.
func (u *SupplierPricingUpsertBulk) SetVersion(v int) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetVersion(v)
	})
}

// AddVersion adds v to the "version" field.
func (u *SupplierPricingUpsertBulk) AddVersion(v int) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddVersion(v)
	})
}

// UpdateVersion sets the "version" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateVersion() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateVersion()
	})
}

// SetTierLabel sets the "tier_label" field.
func (u *SupplierPricingUpsertBulk) SetTierLabel(v string) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetTierLabel(v)
	})
}

// UpdateTierLabel sets the "tier_label" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateTierLabel() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateTierLabel()
	})
}

// ClearTierLabel clears the value of the "tier_label" field.
func (u *SupplierPricingUpsertBulk) ClearTierLabel() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearTierLabel()
	})
}

// SetAvailability sets the "availability" field.
func (u *SupplierPricingUpsertBulk) SetAvailability(v string) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetAvailability(v)
	})
}

// UpdateAvailability sets the "availability" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateAvailability() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateAvailability()
	})
}

// ClearAvailability clears the value of the "availability" field.
func (u *SupplierPricingUpsertBulk) ClearAvailability() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearAvailability()
	})
}

// SetInputRate sets the "input_rate" field.
func (u *SupplierPricingUpsertBulk) SetInputRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetInputRate(v)
	})
}

// AddInputRate adds v to the "input_rate" field.
func (u *SupplierPricingUpsertBulk) AddInputRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddInputRate(v)
	})
}

// UpdateInputRate sets the "input_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateInputRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateInputRate()
	})
}

// ClearInputRate clears the value of the "input_rate" field.
func (u *SupplierPricingUpsertBulk) ClearInputRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearInputRate()
	})
}

// SetOutputRate sets the "output_rate" field.
func (u *SupplierPricingUpsertBulk) SetOutputRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetOutputRate(v)
	})
}

// AddOutputRate adds v to the "output_rate" field.
func (u *SupplierPricingUpsertBulk) AddOutputRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddOutputRate(v)
	})
}

// UpdateOutputRate sets the "output_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateOutputRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateOutputRate()
	})
}

// ClearOutputRate clears the value of the "output_rate" field.
func (u *SupplierPricingUpsertBulk) ClearOutputRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearOutputRate()
	})
}

// SetCachedReadRate sets the "cached_read_rate" field.
func (u *SupplierPricingUpsertBulk) SetCachedReadRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetCachedReadRate(v)
	})
}

// AddCachedReadRate adds v to the "cached_read_rate" field.
func (u *SupplierPricingUpsertBulk) AddCachedReadRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddCachedReadRate(v)
	})
}

// UpdateCachedReadRate sets the "cached_read_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateCachedReadRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateCachedReadRate()
	})
}

// ClearCachedReadRate clears the value of the "cached_read_rate" field.
func (u *SupplierPricingUpsertBulk) ClearCachedReadRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearCachedReadRate()
	})
}

// SetCachedWriteRate sets the "cached_write_rate" field.
func (u *SupplierPricingUpsertBulk) SetCachedWriteRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetCachedWriteRate(v)
	})
}

// AddCachedWriteRate adds v to the "cached_write_rate" field.
func (u *SupplierPricingUpsertBulk) AddCachedWriteRate(v float64) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.AddCachedWriteRate(v)
	})
}

// UpdateCachedWriteRate sets the "cached_write_rate" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateCachedWriteRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateCachedWriteRate()
	})
}

// ClearCachedWriteRate clears the value of the "cached_write_rate" field.
func (u *SupplierPricingUpsertBulk) ClearCachedWriteRate() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearCachedWriteRate()
	})
}

// SetCacheCapabilities sets the "cache_capabilities" field.
func (u *SupplierPricingUpsertBulk) SetCacheCapabilities(v map[string]bool) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetCacheCapabilities(v)
	})
}

// UpdateCacheCapabilities sets the "cache_capabilities" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateCacheCapabilities() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateCacheCapabilities()
	})
}

// ClearCacheCapabilities clears the value of the "cache_capabilities" field.
func (u *SupplierPricingUpsertBulk) ClearCacheCapabilities() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearCacheCapabilities()
	})
}

// SetEffectiveFrom sets the "effective_from" field.
func (u *SupplierPricingUpsertBulk) SetEffectiveFrom(v time.Time) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetEffectiveFrom(v)
	})
}

// UpdateEffectiveFrom sets the "effective_from" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateEffectiveFrom() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateEffectiveFrom()
	})
}

// ClearEffectiveFrom clears the value of the "effective_from" field.
func (u *SupplierPricingUpsertBulk) ClearEffectiveFrom() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearEffectiveFrom()
	})
}

// SetEffectiveTo sets the "effective_to" field.
func (u *SupplierPricingUpsertBulk) SetEffectiveTo(v time.Time) *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.SetEffectiveTo(v)
	})
}

// UpdateEffectiveTo sets the "effective_to" field to the value that was provided on create.
func (u *SupplierPricingUpsertBulk) UpdateEffectiveTo() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.UpdateEffectiveTo()
	})
}

// ClearEffectiveTo clears the value of the "effective_to" field.
func (u *SupplierPricingUpsertBulk) ClearEffectiveTo() *SupplierPricingUpsertBulk {
	return u.Update(func(s *SupplierPricingUpsert) {
		s.ClearEffectiveTo()
	})
}

// Exec executes the query.
func (u *SupplierPricingUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupplierPricingCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierPricingCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierPricingUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
