// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/usagemodelsnapshot"
)

// UsageModelSnapshotUpdate is the builder for updating UsageModelSnapshot entities.
type UsageModelSnapshotUpdate struct {
	config
	hooks    []Hook
	mutation *UsageModelSnapshotMutation
}

// Where appends a list predicates to the UsageModelSnapshotUpdate builder.
func (_u *UsageModelSnapshotUpdate) Where(ps ...predicate.UsageModelSnapshot) *UsageModelSnapshotUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *UsageModelSnapshotUpdate) SetUpdateTime(v time.Time) *UsageModelSnapshotUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UsageModelSnapshotUpdate) SetUserID(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableUserID(v *int64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UsageModelSnapshotUpdate) AddUserID(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *UsageModelSnapshotUpdate) SetModel(v string) *UsageModelSnapshotUpdate {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableModel(v *string) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPricingVersion sets the "pricing_version" field.
func (_u *UsageModelSnapshotUpdate) SetPricingVersion(v int) *UsageModelSnapshotUpdate {
	_u.mutation.ResetPricingVersion()
	_u.mutation.SetPricingVersion(v)
	return _u
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillablePricingVersion(v *int) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetPricingVersion(*v)
	}
	return _u
}

// AddPricingVersion adds value to the "pricing_version" field.
func (_u *UsageModelSnapshotUpdate) AddPricingVersion(v int) *UsageModelSnapshotUpdate {
	_u.mutation.AddPricingVersion(v)
	return _u
}

// SetDisplayInputCost sets the "display_input_cost" field.
func (_u *UsageModelSnapshotUpdate) SetDisplayInputCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetDisplayInputCost()
	_u.mutation.SetDisplayInputCost(v)
	return _u
}

// SetNillableDisplayInputCost sets the "display_input_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableDisplayInputCost(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetDisplayInputCost(*v)
	}
	return _u
}

// AddDisplayInputCost adds value to the "display_input_cost" field.
func (_u *UsageModelSnapshotUpdate) AddDisplayInputCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddDisplayInputCost(v)
	return _u
}

// SetDisplayOutputCost sets the "display_output_cost" field.
func (_u *UsageModelSnapshotUpdate) SetDisplayOutputCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetDisplayOutputCost()
	_u.mutation.SetDisplayOutputCost(v)
	return _u
}

// SetNillableDisplayOutputCost sets the "display_output_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableDisplayOutputCost(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetDisplayOutputCost(*v)
	}
	return _u
}

// AddDisplayOutputCost adds value to the "display_output_cost" field.
func (_u *UsageModelSnapshotUpdate) AddDisplayOutputCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddDisplayOutputCost(v)
	return _u
}

// SetDisplayCacheReadCost sets the "display_cache_read_cost" field.
func (_u *UsageModelSnapshotUpdate) SetDisplayCacheReadCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetDisplayCacheReadCost()
	_u.mutation.SetDisplayCacheReadCost(v)
	return _u
}

// SetNillableDisplayCacheReadCost sets the "display_cache_read_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableDisplayCacheReadCost(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetDisplayCacheReadCost(*v)
	}
	return _u
}

// AddDisplayCacheReadCost adds value to the "display_cache_read_cost" field.
func (_u *UsageModelSnapshotUpdate) AddDisplayCacheReadCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddDisplayCacheReadCost(v)
	return _u
}

// SetDisplayCacheWriteCost sets the "display_cache_write_cost" field.
func (_u *UsageModelSnapshotUpdate) SetDisplayCacheWriteCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetDisplayCacheWriteCost()
	_u.mutation.SetDisplayCacheWriteCost(v)
	return _u
}

// SetNillableDisplayCacheWriteCost sets the "display_cache_write_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableDisplayCacheWriteCost(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetDisplayCacheWriteCost(*v)
	}
	return _u
}

// AddDisplayCacheWriteCost adds value to the "display_cache_write_cost" field.
func (_u *UsageModelSnapshotUpdate) AddDisplayCacheWriteCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddDisplayCacheWriteCost(v)
	return _u
}

// SetDisplayTotalCost sets the "display_total_cost" field.
func (_u *UsageModelSnapshotUpdate) SetDisplayTotalCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetDisplayTotalCost()
	_u.mutation.SetDisplayTotalCost(v)
	return _u
}

// SetNillableDisplayTotalCost sets the "display_total_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableDisplayTotalCost(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetDisplayTotalCost(*v)
	}
	return _u
}

// AddDisplayTotalCost adds value to the "display_total_cost" field.
func (_u *UsageModelSnapshotUpdate) AddDisplayTotalCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddDisplayTotalCost(v)
	return _u
}

// SetDisplayBlendCost sets the "display_blend_cost" field.
func (_u *UsageModelSnapshotUpdate) SetDisplayBlendCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetDisplayBlendCost()
	_u.mutation.SetDisplayBlendCost(v)
	return _u
}

// SetNillableDisplayBlendCost sets the "display_blend_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableDisplayBlendCost(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetDisplayBlendCost(*v)
	}
	return _u
}

// AddDisplayBlendCost adds value to the "display_blend_cost" field.
func (_u *UsageModelSnapshotUpdate) AddDisplayBlendCost(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddDisplayBlendCost(v)
	return _u
}

// SetCostInput sets the "cost_input" field.
func (_u *UsageModelSnapshotUpdate) SetCostInput(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCostInput()
	_u.mutation.SetCostInput(v)
	return _u
}

// SetNillableCostInput sets the "cost_input" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCostInput(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCostInput(*v)
	}
	return _u
}

// AddCostInput adds value to the "cost_input" field.
func (_u *UsageModelSnapshotUpdate) AddCostInput(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCostInput(v)
	return _u
}

// SetCostOutput sets the "cost_output" field.
func (_u *UsageModelSnapshotUpdate) SetCostOutput(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCostOutput()
	_u.mutation.SetCostOutput(v)
	return _u
}

// SetNillableCostOutput sets the "cost_output" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCostOutput(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCostOutput(*v)
	}
	return _u
}

// AddCostOutput adds value to the "cost_output" field.
func (_u *UsageModelSnapshotUpdate) AddCostOutput(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCostOutput(v)
	return _u
}

// SetCostCacheRead sets the "cost_cache_read" field.
func (_u *UsageModelSnapshotUpdate) SetCostCacheRead(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCostCacheRead()
	_u.mutation.SetCostCacheRead(v)
	return _u
}

// SetNillableCostCacheRead sets the "cost_cache_read" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCostCacheRead(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCostCacheRead(*v)
	}
	return _u
}

// AddCostCacheRead adds value to the "cost_cache_read" field.
func (_u *UsageModelSnapshotUpdate) AddCostCacheRead(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCostCacheRead(v)
	return _u
}

// SetCostCacheWrite sets the "cost_cache_write" field.
func (_u *UsageModelSnapshotUpdate) SetCostCacheWrite(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCostCacheWrite()
	_u.mutation.SetCostCacheWrite(v)
	return _u
}

// SetNillableCostCacheWrite sets the "cost_cache_write" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCostCacheWrite(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCostCacheWrite(*v)
	}
	return _u
}

// AddCostCacheWrite adds value to the "cost_cache_write" field.
func (_u *UsageModelSnapshotUpdate) AddCostCacheWrite(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCostCacheWrite(v)
	return _u
}

// SetCostTotal sets the "cost_total" field.
func (_u *UsageModelSnapshotUpdate) SetCostTotal(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCostTotal()
	_u.mutation.SetCostTotal(v)
	return _u
}

// SetNillableCostTotal sets the "cost_total" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCostTotal(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCostTotal(*v)
	}
	return _u
}

// AddCostTotal adds value to the "cost_total" field.
func (_u *UsageModelSnapshotUpdate) AddCostTotal(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCostTotal(v)
	return _u
}

// SetCostSupplierCode sets the "cost_supplier_code" field.
func (_u *UsageModelSnapshotUpdate) SetCostSupplierCode(v string) *UsageModelSnapshotUpdate {
	_u.mutation.SetCostSupplierCode(v)
	return _u
}

// SetNillableCostSupplierCode sets the "cost_supplier_code" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCostSupplierCode(v *string) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCostSupplierCode(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *UsageModelSnapshotUpdate) SetInputTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableInputTokens(v *int64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *UsageModelSnapshotUpdate) AddInputTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *UsageModelSnapshotUpdate) SetOutputTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableOutputTokens(v *int64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *UsageModelSnapshotUpdate) AddOutputTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *UsageModelSnapshotUpdate) SetCacheReadTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCacheReadTokens(v *int64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *UsageModelSnapshotUpdate) AddCacheReadTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheWriteTokens sets the "cache_write_tokens" field.
func (_u *UsageModelSnapshotUpdate) SetCacheWriteTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetCacheWriteTokens()
	_u.mutation.SetCacheWriteTokens(v)
	return _u
}

// SetNillableCacheWriteTokens sets the "cache_write_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableCacheWriteTokens(v *int64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetCacheWriteTokens(*v)
	}
	return _u
}

// AddCacheWriteTokens adds value to the "cache_write_tokens" field.
func (_u *UsageModelSnapshotUpdate) AddCacheWriteTokens(v int64) *UsageModelSnapshotUpdate {
	_u.mutation.AddCacheWriteTokens(v)
	return _u
}

// SetUsageModelPct sets the "usage_model_pct" field.
func (_u *UsageModelSnapshotUpdate) SetUsageModelPct(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.ResetUsageModelPct()
	_u.mutation.SetUsageModelPct(v)
	return _u
}

// SetNillableUsageModelPct sets the "usage_model_pct" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdate) SetNillableUsageModelPct(v *float64) *UsageModelSnapshotUpdate {
	if v != nil {
		_u.SetUsageModelPct(*v)
	}
	return _u
}

// AddUsageModelPct adds value to the "usage_model_pct" field.
func (_u *UsageModelSnapshotUpdate) AddUsageModelPct(v float64) *UsageModelSnapshotUpdate {
	_u.mutation.AddUsageModelPct(v)
	return _u
}

// Mutation returns the UsageModelSnapshotMutation object of the builder.
func (_u *UsageModelSnapshotUpdate) Mutation() *UsageModelSnapshotMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UsageModelSnapshotUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageModelSnapshotUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UsageModelSnapshotUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageModelSnapshotUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageModelSnapshotUpdate) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := usagemodelsnapshot.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageModelSnapshotUpdate) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := usagemodelsnapshot.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageModelSnapshot.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostSupplierCode(); ok {
		if err := usagemodelsnapshot.CostSupplierCodeValidator(v); err != nil {
			return &ValidationError{Name: "cost_supplier_code", err: fmt.Errorf(`ent: validator failed for field "UsageModelSnapshot.cost_supplier_code": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageModelSnapshotUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagemodelsnapshot.Table, usagemodelsnapshot.Columns, sqlgraph.NewFieldSpec(usagemodelsnapshot.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(usagemodelsnapshot.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usagemodelsnapshot.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usagemodelsnapshot.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(usagemodelsnapshot.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingVersion(); ok {
		_spec.SetField(usagemodelsnapshot.FieldPricingVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricingVersion(); ok {
		_spec.AddField(usagemodelsnapshot.FieldPricingVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DisplayInputCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayInputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayInputCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayInputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayOutputCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayOutputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayOutputCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayOutputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayCacheReadCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayCacheReadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayCacheReadCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayCacheReadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayCacheWriteCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayCacheWriteCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayCacheWriteCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayCacheWriteCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayTotalCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayTotalCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayBlendCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayBlendCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayBlendCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayBlendCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostInput(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostInput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostInput(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostInput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostOutput(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostOutput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostOutput(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostOutput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostCacheRead(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostCacheRead, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostCacheRead(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostCacheRead, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostCacheWrite(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostCacheWrite, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostCacheWrite(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostCacheWrite, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostTotal(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostTotal(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostSupplierCode(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostSupplierCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWriteTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWriteTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageModelPct(); ok {
		_spec.SetField(usagemodelsnapshot.FieldUsageModelPct, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsageModelPct(); ok {
		_spec.AddField(usagemodelsnapshot.FieldUsageModelPct, field.TypeFloat64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagemodelsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UsageModelSnapshotUpdateOne is the builder for updating a single UsageModelSnapshot entity.
type UsageModelSnapshotUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UsageModelSnapshotMutation
}

// SetUpdateTime sets the "update_time" field.
func (_u *UsageModelSnapshotUpdateOne) SetUpdateTime(v time.Time) *UsageModelSnapshotUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UsageModelSnapshotUpdateOne) SetUserID(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableUserID(v *int64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *UsageModelSnapshotUpdateOne) AddUserID(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetModel sets the "model" field.
func (_u *UsageModelSnapshotUpdateOne) SetModel(v string) *UsageModelSnapshotUpdateOne {
	_u.mutation.SetModel(v)
	return _u
}

// SetNillableModel sets the "model" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableModel(v *string) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetModel(*v)
	}
	return _u
}

// SetPricingVersion sets the "pricing_version" field.
func (_u *UsageModelSnapshotUpdateOne) SetPricingVersion(v int) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetPricingVersion()
	_u.mutation.SetPricingVersion(v)
	return _u
}

// SetNillablePricingVersion sets the "pricing_version" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillablePricingVersion(v *int) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetPricingVersion(*v)
	}
	return _u
}

// AddPricingVersion adds value to the "pricing_version" field.
func (_u *UsageModelSnapshotUpdateOne) AddPricingVersion(v int) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddPricingVersion(v)
	return _u
}

// SetDisplayInputCost sets the "display_input_cost" field.
func (_u *UsageModelSnapshotUpdateOne) SetDisplayInputCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetDisplayInputCost()
	_u.mutation.SetDisplayInputCost(v)
	return _u
}

// SetNillableDisplayInputCost sets the "display_input_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableDisplayInputCost(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayInputCost(*v)
	}
	return _u
}

// AddDisplayInputCost adds value to the "display_input_cost" field.
func (_u *UsageModelSnapshotUpdateOne) AddDisplayInputCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddDisplayInputCost(v)
	return _u
}

// SetDisplayOutputCost sets the "display_output_cost" field.
func (_u *UsageModelSnapshotUpdateOne) SetDisplayOutputCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetDisplayOutputCost()
	_u.mutation.SetDisplayOutputCost(v)
	return _u
}

// SetNillableDisplayOutputCost sets the "display_output_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableDisplayOutputCost(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayOutputCost(*v)
	}
	return _u
}

// AddDisplayOutputCost adds value to the "display_output_cost" field.
func (_u *UsageModelSnapshotUpdateOne) AddDisplayOutputCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddDisplayOutputCost(v)
	return _u
}

// SetDisplayCacheReadCost sets the "display_cache_read_cost" field.
func (_u *UsageModelSnapshotUpdateOne) SetDisplayCacheReadCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetDisplayCacheReadCost()
	_u.mutation.SetDisplayCacheReadCost(v)
	return _u
}

// SetNillableDisplayCacheReadCost sets the "display_cache_read_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableDisplayCacheReadCost(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayCacheReadCost(*v)
	}
	return _u
}

// AddDisplayCacheReadCost adds value to the "display_cache_read_cost" field.
func (_u *UsageModelSnapshotUpdateOne) AddDisplayCacheReadCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddDisplayCacheReadCost(v)
	return _u
}

// SetDisplayCacheWriteCost sets the "display_cache_write_cost" field.
func (_u *UsageModelSnapshotUpdateOne) SetDisplayCacheWriteCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetDisplayCacheWriteCost()
	_u.mutation.SetDisplayCacheWriteCost(v)
	return _u
}

// SetNillableDisplayCacheWriteCost sets the "display_cache_write_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableDisplayCacheWriteCost(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayCacheWriteCost(*v)
	}
	return _u
}

// AddDisplayCacheWriteCost adds value to the "display_cache_write_cost" field.
func (_u *UsageModelSnapshotUpdateOne) AddDisplayCacheWriteCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddDisplayCacheWriteCost(v)
	return _u
}

// SetDisplayTotalCost sets the "display_total_cost" field.
func (_u *UsageModelSnapshotUpdateOne) SetDisplayTotalCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetDisplayTotalCost()
	_u.mutation.SetDisplayTotalCost(v)
	return _u
}

// SetNillableDisplayTotalCost sets the "display_total_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableDisplayTotalCost(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayTotalCost(*v)
	}
	return _u
}

// AddDisplayTotalCost adds value to the "display_total_cost" field.
func (_u *UsageModelSnapshotUpdateOne) AddDisplayTotalCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddDisplayTotalCost(v)
	return _u
}

// SetDisplayBlendCost sets the "display_blend_cost" field.
func (_u *UsageModelSnapshotUpdateOne) SetDisplayBlendCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetDisplayBlendCost()
	_u.mutation.SetDisplayBlendCost(v)
	return _u
}

// SetNillableDisplayBlendCost sets the "display_blend_cost" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableDisplayBlendCost(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetDisplayBlendCost(*v)
	}
	return _u
}

// AddDisplayBlendCost adds value to the "display_blend_cost" field.
func (_u *UsageModelSnapshotUpdateOne) AddDisplayBlendCost(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddDisplayBlendCost(v)
	return _u
}

// SetCostInput sets the "cost_input" field.
func (_u *UsageModelSnapshotUpdateOne) SetCostInput(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCostInput()
	_u.mutation.SetCostInput(v)
	return _u
}

// SetNillableCostInput sets the "cost_input" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCostInput(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCostInput(*v)
	}
	return _u
}

// AddCostInput adds value to the "cost_input" field.
func (_u *UsageModelSnapshotUpdateOne) AddCostInput(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCostInput(v)
	return _u
}

// SetCostOutput sets the "cost_output" field.
func (_u *UsageModelSnapshotUpdateOne) SetCostOutput(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCostOutput()
	_u.mutation.SetCostOutput(v)
	return _u
}

// SetNillableCostOutput sets the "cost_output" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCostOutput(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCostOutput(*v)
	}
	return _u
}

// AddCostOutput adds value to the "cost_output" field.
func (_u *UsageModelSnapshotUpdateOne) AddCostOutput(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCostOutput(v)
	return _u
}

// SetCostCacheRead sets the "cost_cache_read" field.
func (_u *UsageModelSnapshotUpdateOne) SetCostCacheRead(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCostCacheRead()
	_u.mutation.SetCostCacheRead(v)
	return _u
}

// SetNillableCostCacheRead sets the "cost_cache_read" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCostCacheRead(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCostCacheRead(*v)
	}
	return _u
}

// AddCostCacheRead adds value to the "cost_cache_read" field.
func (_u *UsageModelSnapshotUpdateOne) AddCostCacheRead(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCostCacheRead(v)
	return _u
}

// SetCostCacheWrite sets the "cost_cache_write" field.
func (_u *UsageModelSnapshotUpdateOne) SetCostCacheWrite(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCostCacheWrite()
	_u.mutation.SetCostCacheWrite(v)
	return _u
}

// SetNillableCostCacheWrite sets the "cost_cache_write" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCostCacheWrite(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCostCacheWrite(*v)
	}
	return _u
}

// AddCostCacheWrite adds value to the "cost_cache_write" field.
func (_u *UsageModelSnapshotUpdateOne) AddCostCacheWrite(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCostCacheWrite(v)
	return _u
}

// SetCostTotal sets the "cost_total" field.
func (_u *UsageModelSnapshotUpdateOne) SetCostTotal(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCostTotal()
	_u.mutation.SetCostTotal(v)
	return _u
}

// SetNillableCostTotal sets the "cost_total" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCostTotal(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCostTotal(*v)
	}
	return _u
}

// AddCostTotal adds value to the "cost_total" field.
func (_u *UsageModelSnapshotUpdateOne) AddCostTotal(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCostTotal(v)
	return _u
}

// SetCostSupplierCode sets the "cost_supplier_code" field.
func (_u *UsageModelSnapshotUpdateOne) SetCostSupplierCode(v string) *UsageModelSnapshotUpdateOne {
	_u.mutation.SetCostSupplierCode(v)
	return _u
}

// SetNillableCostSupplierCode sets the "cost_supplier_code" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCostSupplierCode(v *string) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCostSupplierCode(*v)
	}
	return _u
}

// SetInputTokens sets the "input_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) SetInputTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetInputTokens()
	_u.mutation.SetInputTokens(v)
	return _u
}

// SetNillableInputTokens sets the "input_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableInputTokens(v *int64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetInputTokens(*v)
	}
	return _u
}

// AddInputTokens adds value to the "input_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) AddInputTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddInputTokens(v)
	return _u
}

// SetOutputTokens sets the "output_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) SetOutputTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetOutputTokens()
	_u.mutation.SetOutputTokens(v)
	return _u
}

// SetNillableOutputTokens sets the "output_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableOutputTokens(v *int64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetOutputTokens(*v)
	}
	return _u
}

// AddOutputTokens adds value to the "output_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) AddOutputTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddOutputTokens(v)
	return _u
}

// SetCacheReadTokens sets the "cache_read_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) SetCacheReadTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCacheReadTokens()
	_u.mutation.SetCacheReadTokens(v)
	return _u
}

// SetNillableCacheReadTokens sets the "cache_read_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCacheReadTokens(v *int64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCacheReadTokens(*v)
	}
	return _u
}

// AddCacheReadTokens adds value to the "cache_read_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) AddCacheReadTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCacheReadTokens(v)
	return _u
}

// SetCacheWriteTokens sets the "cache_write_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) SetCacheWriteTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetCacheWriteTokens()
	_u.mutation.SetCacheWriteTokens(v)
	return _u
}

// SetNillableCacheWriteTokens sets the "cache_write_tokens" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableCacheWriteTokens(v *int64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetCacheWriteTokens(*v)
	}
	return _u
}

// AddCacheWriteTokens adds value to the "cache_write_tokens" field.
func (_u *UsageModelSnapshotUpdateOne) AddCacheWriteTokens(v int64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddCacheWriteTokens(v)
	return _u
}

// SetUsageModelPct sets the "usage_model_pct" field.
func (_u *UsageModelSnapshotUpdateOne) SetUsageModelPct(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.ResetUsageModelPct()
	_u.mutation.SetUsageModelPct(v)
	return _u
}

// SetNillableUsageModelPct sets the "usage_model_pct" field if the given value is not nil.
func (_u *UsageModelSnapshotUpdateOne) SetNillableUsageModelPct(v *float64) *UsageModelSnapshotUpdateOne {
	if v != nil {
		_u.SetUsageModelPct(*v)
	}
	return _u
}

// AddUsageModelPct adds value to the "usage_model_pct" field.
func (_u *UsageModelSnapshotUpdateOne) AddUsageModelPct(v float64) *UsageModelSnapshotUpdateOne {
	_u.mutation.AddUsageModelPct(v)
	return _u
}

// Mutation returns the UsageModelSnapshotMutation object of the builder.
func (_u *UsageModelSnapshotUpdateOne) Mutation() *UsageModelSnapshotMutation {
	return _u.mutation
}

// Where appends a list predicates to the UsageModelSnapshotUpdate builder.
func (_u *UsageModelSnapshotUpdateOne) Where(ps ...predicate.UsageModelSnapshot) *UsageModelSnapshotUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UsageModelSnapshotUpdateOne) Select(field string, fields ...string) *UsageModelSnapshotUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UsageModelSnapshot entity.
func (_u *UsageModelSnapshotUpdateOne) Save(ctx context.Context) (*UsageModelSnapshot, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UsageModelSnapshotUpdateOne) SaveX(ctx context.Context) *UsageModelSnapshot {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UsageModelSnapshotUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UsageModelSnapshotUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UsageModelSnapshotUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		v := usagemodelsnapshot.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UsageModelSnapshotUpdateOne) check() error {
	if v, ok := _u.mutation.Model(); ok {
		if err := usagemodelsnapshot.ModelValidator(v); err != nil {
			return &ValidationError{Name: "model", err: fmt.Errorf(`ent: validator failed for field "UsageModelSnapshot.model": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CostSupplierCode(); ok {
		if err := usagemodelsnapshot.CostSupplierCodeValidator(v); err != nil {
			return &ValidationError{Name: "cost_supplier_code", err: fmt.Errorf(`ent: validator failed for field "UsageModelSnapshot.cost_supplier_code": %w`, err)}
		}
	}
	return nil
}

func (_u *UsageModelSnapshotUpdateOne) sqlSave(ctx context.Context) (_node *UsageModelSnapshot, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usagemodelsnapshot.Table, usagemodelsnapshot.Columns, sqlgraph.NewFieldSpec(usagemodelsnapshot.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsageModelSnapshot.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usagemodelsnapshot.FieldID)
		for _, f := range fields {
			if !usagemodelsnapshot.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usagemodelsnapshot.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(usagemodelsnapshot.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(usagemodelsnapshot.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(usagemodelsnapshot.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Model(); ok {
		_spec.SetField(usagemodelsnapshot.FieldModel, field.TypeString, value)
	}
	if value, ok := _u.mutation.PricingVersion(); ok {
		_spec.SetField(usagemodelsnapshot.FieldPricingVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPricingVersion(); ok {
		_spec.AddField(usagemodelsnapshot.FieldPricingVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DisplayInputCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayInputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayInputCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayInputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayOutputCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayOutputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayOutputCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayOutputCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayCacheReadCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayCacheReadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayCacheReadCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayCacheReadCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayCacheWriteCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayCacheWriteCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayCacheWriteCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayCacheWriteCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayTotalCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayTotalCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayTotalCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DisplayBlendCost(); ok {
		_spec.SetField(usagemodelsnapshot.FieldDisplayBlendCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDisplayBlendCost(); ok {
		_spec.AddField(usagemodelsnapshot.FieldDisplayBlendCost, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostInput(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostInput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostInput(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostInput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostOutput(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostOutput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostOutput(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostOutput, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostCacheRead(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostCacheRead, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostCacheRead(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostCacheRead, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostCacheWrite(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostCacheWrite, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostCacheWrite(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostCacheWrite, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostTotal(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCostTotal(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCostTotal, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CostSupplierCode(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCostSupplierCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.InputTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInputTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldInputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OutputTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOutputTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldOutputTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheReadTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheReadTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCacheReadTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CacheWriteTokens(); ok {
		_spec.SetField(usagemodelsnapshot.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCacheWriteTokens(); ok {
		_spec.AddField(usagemodelsnapshot.FieldCacheWriteTokens, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UsageModelPct(); ok {
		_spec.SetField(usagemodelsnapshot.FieldUsageModelPct, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedUsageModelPct(); ok {
		_spec.AddField(usagemodelsnapshot.FieldUsageModelPct, field.TypeFloat64, value)
	}
	_node = &UsageModelSnapshot{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usagemodelsnapshot.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
