// Code generated by ent, DO NOT EDIT.

package qrispayment

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContainsFold(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldUserID, v))
}

// AmountIdr applies equality check predicate on the "amount_idr" field. It's identical to AmountIdrEQ.
func AmountIdr(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldAmountIdr, v))
}

// PaymentRef applies equality check predicate on the "payment_ref" field. It's identical to PaymentRefEQ.
func PaymentRef(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldPaymentRef, v))
}

// QrString applies equality check predicate on the "qr_string" field. It's identical to QrStringEQ.
func QrString(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldQrString, v))
}

// ImageBase64 applies equality check predicate on the "image_base64" field. It's identical to ImageBase64EQ.
func ImageBase64(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldImageBase64, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldExpiresAt, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldStatus, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldUserID, v))
}

// AmountIdrEQ applies the EQ predicate on the "amount_idr" field.
func AmountIdrEQ(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldAmountIdr, v))
}

// AmountIdrNEQ applies the NEQ predicate on the "amount_idr" field.
func AmountIdrNEQ(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldAmountIdr, v))
}

// AmountIdrIn applies the In predicate on the "amount_idr" field.
func AmountIdrIn(vs ...int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldAmountIdr, vs...))
}

// AmountIdrNotIn applies the NotIn predicate on the "amount_idr" field.
func AmountIdrNotIn(vs ...int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldAmountIdr, vs...))
}

// AmountIdrGT applies the GT predicate on the "amount_idr" field.
func AmountIdrGT(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldAmountIdr, v))
}

// AmountIdrGTE applies the GTE predicate on the "amount_idr" field.
func AmountIdrGTE(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldAmountIdr, v))
}

// AmountIdrLT applies the LT predicate on the "amount_idr" field.
func AmountIdrLT(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldAmountIdr, v))
}

// AmountIdrLTE applies the LTE predicate on the "amount_idr" field.
func AmountIdrLTE(v int64) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldAmountIdr, v))
}

// PaymentRefEQ applies the EQ predicate on the "payment_ref" field.
func PaymentRefEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldPaymentRef, v))
}

// PaymentRefNEQ applies the NEQ predicate on the "payment_ref" field.
func PaymentRefNEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldPaymentRef, v))
}

// PaymentRefIn applies the In predicate on the "payment_ref" field.
func PaymentRefIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldPaymentRef, vs...))
}

// PaymentRefNotIn applies the NotIn predicate on the "payment_ref" field.
func PaymentRefNotIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldPaymentRef, vs...))
}

// PaymentRefGT applies the GT predicate on the "payment_ref" field.
func PaymentRefGT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldPaymentRef, v))
}

// PaymentRefGTE applies the GTE predicate on the "payment_ref" field.
func PaymentRefGTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldPaymentRef, v))
}

// PaymentRefLT applies the LT predicate on the "payment_ref" field.
func PaymentRefLT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldPaymentRef, v))
}

// PaymentRefLTE applies the LTE predicate on the "payment_ref" field.
func PaymentRefLTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldPaymentRef, v))
}

// PaymentRefContains applies the Contains predicate on the "payment_ref" field.
func PaymentRefContains(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContains(FieldPaymentRef, v))
}

// PaymentRefHasPrefix applies the HasPrefix predicate on the "payment_ref" field.
func PaymentRefHasPrefix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasPrefix(FieldPaymentRef, v))
}

// PaymentRefHasSuffix applies the HasSuffix predicate on the "payment_ref" field.
func PaymentRefHasSuffix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasSuffix(FieldPaymentRef, v))
}

// PaymentRefEqualFold applies the EqualFold predicate on the "payment_ref" field.
func PaymentRefEqualFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEqualFold(FieldPaymentRef, v))
}

// PaymentRefContainsFold applies the ContainsFold predicate on the "payment_ref" field.
func PaymentRefContainsFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContainsFold(FieldPaymentRef, v))
}

// QrStringEQ applies the EQ predicate on the "qr_string" field.
func QrStringEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldQrString, v))
}

// QrStringNEQ applies the NEQ predicate on the "qr_string" field.
func QrStringNEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldQrString, v))
}

// QrStringIn applies the In predicate on the "qr_string" field.
func QrStringIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldQrString, vs...))
}

// QrStringNotIn applies the NotIn predicate on the "qr_string" field.
func QrStringNotIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldQrString, vs...))
}

// QrStringGT applies the GT predicate on the "qr_string" field.
func QrStringGT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldQrString, v))
}

// QrStringGTE applies the GTE predicate on the "qr_string" field.
func QrStringGTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldQrString, v))
}

// QrStringLT applies the LT predicate on the "qr_string" field.
func QrStringLT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldQrString, v))
}

// QrStringLTE applies the LTE predicate on the "qr_string" field.
func QrStringLTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldQrString, v))
}

// QrStringContains applies the Contains predicate on the "qr_string" field.
func QrStringContains(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContains(FieldQrString, v))
}

// QrStringHasPrefix applies the HasPrefix predicate on the "qr_string" field.
func QrStringHasPrefix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasPrefix(FieldQrString, v))
}

// QrStringHasSuffix applies the HasSuffix predicate on the "qr_string" field.
func QrStringHasSuffix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasSuffix(FieldQrString, v))
}

// QrStringEqualFold applies the EqualFold predicate on the "qr_string" field.
func QrStringEqualFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEqualFold(FieldQrString, v))
}

// QrStringContainsFold applies the ContainsFold predicate on the "qr_string" field.
func QrStringContainsFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContainsFold(FieldQrString, v))
}

// ImageBase64EQ applies the EQ predicate on the "image_base64" field.
func ImageBase64EQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldImageBase64, v))
}

// ImageBase64NEQ applies the NEQ predicate on the "image_base64" field.
func ImageBase64NEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldImageBase64, v))
}

// ImageBase64In applies the In predicate on the "image_base64" field.
func ImageBase64In(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldImageBase64, vs...))
}

// ImageBase64NotIn applies the NotIn predicate on the "image_base64" field.
func ImageBase64NotIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldImageBase64, vs...))
}

// ImageBase64GT applies the GT predicate on the "image_base64" field.
func ImageBase64GT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldImageBase64, v))
}

// ImageBase64GTE applies the GTE predicate on the "image_base64" field.
func ImageBase64GTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldImageBase64, v))
}

// ImageBase64LT applies the LT predicate on the "image_base64" field.
func ImageBase64LT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldImageBase64, v))
}

// ImageBase64LTE applies the LTE predicate on the "image_base64" field.
func ImageBase64LTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldImageBase64, v))
}

// ImageBase64Contains applies the Contains predicate on the "image_base64" field.
func ImageBase64Contains(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContains(FieldImageBase64, v))
}

// ImageBase64HasPrefix applies the HasPrefix predicate on the "image_base64" field.
func ImageBase64HasPrefix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasPrefix(FieldImageBase64, v))
}

// ImageBase64HasSuffix applies the HasSuffix predicate on the "image_base64" field.
func ImageBase64HasSuffix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasSuffix(FieldImageBase64, v))
}

// ImageBase64EqualFold applies the EqualFold predicate on the "image_base64" field.
func ImageBase64EqualFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEqualFold(FieldImageBase64, v))
}

// ImageBase64ContainsFold applies the ContainsFold predicate on the "image_base64" field.
func ImageBase64ContainsFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContainsFold(FieldImageBase64, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldExpiresAt, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContainsFold(FieldStatus, v))
}

// GomerchPayloadIsNil applies the IsNil predicate on the "gomerch_payload" field.
func GomerchPayloadIsNil() predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIsNull(FieldGomerchPayload))
}

// GomerchPayloadNotNil applies the NotNil predicate on the "gomerch_payload" field.
func GomerchPayloadNotNil() predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotNull(FieldGomerchPayload))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyIsNil applies the IsNil predicate on the "idempotency_key" field.
func IdempotencyKeyIsNil() predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIsNull(FieldIdempotencyKey))
}

// IdempotencyKeyNotNil applies the NotNil predicate on the "idempotency_key" field.
func IdempotencyKeyNotNil() predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotNull(FieldIdempotencyKey))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.QrisPayment {
	return predicate.QrisPayment(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPaymentOrders applies the HasEdge predicate on the "payment_orders" edge.
func HasPaymentOrders() predicate.QrisPayment {
	return predicate.QrisPayment(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PaymentOrdersTable, PaymentOrdersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPaymentOrdersWith applies the HasEdge predicate on the "payment_orders" edge with a given conditions (other predicates).
func HasPaymentOrdersWith(preds ...predicate.PaymentOrder) predicate.QrisPayment {
	return predicate.QrisPayment(func(s *sql.Selector) {
		step := newPaymentOrdersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.QrisPayment) predicate.QrisPayment {
	return predicate.QrisPayment(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.QrisPayment) predicate.QrisPayment {
	return predicate.QrisPayment(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.QrisPayment) predicate.QrisPayment {
	return predicate.QrisPayment(sql.NotPredicates(p))
}
