// Code generated by ent, DO NOT EDIT.

package supplierpricing

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the supplierpricing type in the database.
	Label = "supplier_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldSupplierCode holds the string denoting the supplier_code field in the database.
	FieldSupplierCode = "supplier_code"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldTierLabel holds the string denoting the tier_label field in the database.
	FieldTierLabel = "tier_label"
	// FieldAvailability holds the string denoting the availability field in the database.
	FieldAvailability = "availability"
	// FieldInputRate holds the string denoting the input_rate field in the database.
	FieldInputRate = "input_rate"
	// FieldOutputRate holds the string denoting the output_rate field in the database.
	FieldOutputRate = "output_rate"
	// FieldCachedReadRate holds the string denoting the cached_read_rate field in the database.
	FieldCachedReadRate = "cached_read_rate"
	// FieldCachedWriteRate holds the string denoting the cached_write_rate field in the database.
	FieldCachedWriteRate = "cached_write_rate"
	// FieldCacheCapabilities holds the string denoting the cache_capabilities field in the database.
	FieldCacheCapabilities = "cache_capabilities"
	// FieldEffectiveFrom holds the string denoting the effective_from field in the database.
	FieldEffectiveFrom = "effective_from"
	// FieldEffectiveTo holds the string denoting the effective_to field in the database.
	FieldEffectiveTo = "effective_to"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// Table holds the table name of the supplierpricing in the database.
	Table = "supplier_pricing"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "supplier_pricing"
	// ModelInverseTable is the table name for the ModelCatalog entity.
	// It exists in this package in order to avoid circular dependency with the "modelcatalog" package.
	ModelInverseTable = "model_catalog"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_id"
)

// Columns holds all SQL columns for supplierpricing fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldSupplierCode,
	FieldVersion,
	FieldTierLabel,
	FieldAvailability,
	FieldInputRate,
	FieldOutputRate,
	FieldCachedReadRate,
	FieldCachedWriteRate,
	FieldCacheCapabilities,
	FieldEffectiveFrom,
	FieldEffectiveTo,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// SupplierCodeValidator is a validator for the "supplier_code" field. It is called by the builders before save.
	SupplierCodeValidator func(string) error
	// TierLabelValidator is a validator for the "tier_label" field. It is called by the builders before save.
	TierLabelValidator func(string) error
	// AvailabilityValidator is a validator for the "availability" field. It is called by the builders before save.
	AvailabilityValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the SupplierPricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// BySupplierCode orders the results by the supplier_code field.
func BySupplierCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupplierCode, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByTierLabel orders the results by the tier_label field.
func ByTierLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTierLabel, opts...).ToFunc()
}

// ByAvailability orders the results by the availability field.
func ByAvailability(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvailability, opts...).ToFunc()
}

// ByInputRate orders the results by the input_rate field.
func ByInputRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputRate, opts...).ToFunc()
}

// ByOutputRate orders the results by the output_rate field.
func ByOutputRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputRate, opts...).ToFunc()
}

// ByCachedReadRate orders the results by the cached_read_rate field.
func ByCachedReadRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedReadRate, opts...).ToFunc()
}

// ByCachedWriteRate orders the results by the cached_write_rate field.
func ByCachedWriteRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedWriteRate, opts...).ToFunc()
}

// ByEffectiveFrom orders the results by the effective_from field.
func ByEffectiveFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveFrom, opts...).ToFunc()
}

// ByEffectiveTo orders the results by the effective_to field.
func ByEffectiveTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveTo, opts...).ToFunc()
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
