// Code generated by ent, DO NOT EDIT.

package supplierpricing

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContainsFold(FieldID, id))
}

// ModelID applies equality check predicate on the "model_id" field. It's identical to ModelIDEQ.
func ModelID(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldModelID, v))
}

// SupplierCode applies equality check predicate on the "supplier_code" field. It's identical to SupplierCodeEQ.
func SupplierCode(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldSupplierCode, v))
}

// Version applies equality check predicate on the "version" field. It's identical to VersionEQ.
func Version(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldVersion, v))
}

// TierLabel applies equality check predicate on the "tier_label" field. It's identical to TierLabelEQ.
func TierLabel(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldTierLabel, v))
}

// Availability applies equality check predicate on the "availability" field. It's identical to AvailabilityEQ.
func Availability(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldAvailability, v))
}

// InputRate applies equality check predicate on the "input_rate" field. It's identical to InputRateEQ.
func InputRate(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldInputRate, v))
}

// OutputRate applies equality check predicate on the "output_rate" field. It's identical to OutputRateEQ.
func OutputRate(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldOutputRate, v))
}

// CachedReadRate applies equality check predicate on the "cached_read_rate" field. It's identical to CachedReadRateEQ.
func CachedReadRate(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldCachedReadRate, v))
}

// CachedWriteRate applies equality check predicate on the "cached_write_rate" field. It's identical to CachedWriteRateEQ.
func CachedWriteRate(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldCachedWriteRate, v))
}

// EffectiveFrom applies equality check predicate on the "effective_from" field. It's identical to EffectiveFromEQ.
func EffectiveFrom(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveTo applies equality check predicate on the "effective_to" field. It's identical to EffectiveToEQ.
func EffectiveTo(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldEffectiveTo, v))
}

// ModelIDEQ applies the EQ predicate on the "model_id" field.
func ModelIDEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldModelID, v))
}

// ModelIDNEQ applies the NEQ predicate on the "model_id" field.
func ModelIDNEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldModelID, v))
}

// ModelIDIn applies the In predicate on the "model_id" field.
func ModelIDIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldModelID, vs...))
}

// ModelIDNotIn applies the NotIn predicate on the "model_id" field.
func ModelIDNotIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldModelID, vs...))
}

// ModelIDGT applies the GT predicate on the "model_id" field.
func ModelIDGT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldModelID, v))
}

// ModelIDGTE applies the GTE predicate on the "model_id" field.
func ModelIDGTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldModelID, v))
}

// ModelIDLT applies the LT predicate on the "model_id" field.
func ModelIDLT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldModelID, v))
}

// ModelIDLTE applies the LTE predicate on the "model_id" field.
func ModelIDLTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldModelID, v))
}

// ModelIDContains applies the Contains predicate on the "model_id" field.
func ModelIDContains(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContains(FieldModelID, v))
}

// ModelIDHasPrefix applies the HasPrefix predicate on the "model_id" field.
func ModelIDHasPrefix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasPrefix(FieldModelID, v))
}

// ModelIDHasSuffix applies the HasSuffix predicate on the "model_id" field.
func ModelIDHasSuffix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasSuffix(FieldModelID, v))
}

// ModelIDIsNil applies the IsNil predicate on the "model_id" field.
func ModelIDIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldModelID))
}

// ModelIDNotNil applies the NotNil predicate on the "model_id" field.
func ModelIDNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldModelID))
}

// ModelIDEqualFold applies the EqualFold predicate on the "model_id" field.
func ModelIDEqualFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEqualFold(FieldModelID, v))
}

// ModelIDContainsFold applies the ContainsFold predicate on the "model_id" field.
func ModelIDContainsFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContainsFold(FieldModelID, v))
}

// SupplierCodeEQ applies the EQ predicate on the "supplier_code" field.
func SupplierCodeEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldSupplierCode, v))
}

// SupplierCodeNEQ applies the NEQ predicate on the "supplier_code" field.
func SupplierCodeNEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldSupplierCode, v))
}

// SupplierCodeIn applies the In predicate on the "supplier_code" field.
func SupplierCodeIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldSupplierCode, vs...))
}

// SupplierCodeNotIn applies the NotIn predicate on the "supplier_code" field.
func SupplierCodeNotIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldSupplierCode, vs...))
}

// SupplierCodeGT applies the GT predicate on the "supplier_code" field.
func SupplierCodeGT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldSupplierCode, v))
}

// SupplierCodeGTE applies the GTE predicate on the "supplier_code" field.
func SupplierCodeGTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldSupplierCode, v))
}

// SupplierCodeLT applies the LT predicate on the "supplier_code" field.
func SupplierCodeLT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldSupplierCode, v))
}

// SupplierCodeLTE applies the LTE predicate on the "supplier_code" field.
func SupplierCodeLTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldSupplierCode, v))
}

// SupplierCodeContains applies the Contains predicate on the "supplier_code" field.
func SupplierCodeContains(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContains(FieldSupplierCode, v))
}

// SupplierCodeHasPrefix applies the HasPrefix predicate on the "supplier_code" field.
func SupplierCodeHasPrefix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasPrefix(FieldSupplierCode, v))
}

// SupplierCodeHasSuffix applies the HasSuffix predicate on the "supplier_code" field.
func SupplierCodeHasSuffix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasSuffix(FieldSupplierCode, v))
}

// SupplierCodeEqualFold applies the EqualFold predicate on the "supplier_code" field.
func SupplierCodeEqualFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEqualFold(FieldSupplierCode, v))
}

// SupplierCodeContainsFold applies the ContainsFold predicate on the "supplier_code" field.
func SupplierCodeContainsFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContainsFold(FieldSupplierCode, v))
}

// VersionEQ applies the EQ predicate on the "version" field.
func VersionEQ(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldVersion, v))
}

// VersionNEQ applies the NEQ predicate on the "version" field.
func VersionNEQ(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldVersion, v))
}

// VersionIn applies the In predicate on the "version" field.
func VersionIn(vs ...int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldVersion, vs...))
}

// VersionNotIn applies the NotIn predicate on the "version" field.
func VersionNotIn(vs ...int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldVersion, vs...))
}

// VersionGT applies the GT predicate on the "version" field.
func VersionGT(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldVersion, v))
}

// VersionGTE applies the GTE predicate on the "version" field.
func VersionGTE(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldVersion, v))
}

// VersionLT applies the LT predicate on the "version" field.
func VersionLT(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldVersion, v))
}

// VersionLTE applies the LTE predicate on the "version" field.
func VersionLTE(v int) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldVersion, v))
}

// TierLabelEQ applies the EQ predicate on the "tier_label" field.
func TierLabelEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldTierLabel, v))
}

// TierLabelNEQ applies the NEQ predicate on the "tier_label" field.
func TierLabelNEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldTierLabel, v))
}

// TierLabelIn applies the In predicate on the "tier_label" field.
func TierLabelIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldTierLabel, vs...))
}

// TierLabelNotIn applies the NotIn predicate on the "tier_label" field.
func TierLabelNotIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldTierLabel, vs...))
}

// TierLabelGT applies the GT predicate on the "tier_label" field.
func TierLabelGT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldTierLabel, v))
}

// TierLabelGTE applies the GTE predicate on the "tier_label" field.
func TierLabelGTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldTierLabel, v))
}

// TierLabelLT applies the LT predicate on the "tier_label" field.
func TierLabelLT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldTierLabel, v))
}

// TierLabelLTE applies the LTE predicate on the "tier_label" field.
func TierLabelLTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldTierLabel, v))
}

// TierLabelContains applies the Contains predicate on the "tier_label" field.
func TierLabelContains(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContains(FieldTierLabel, v))
}

// TierLabelHasPrefix applies the HasPrefix predicate on the "tier_label" field.
func TierLabelHasPrefix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasPrefix(FieldTierLabel, v))
}

// TierLabelHasSuffix applies the HasSuffix predicate on the "tier_label" field.
func TierLabelHasSuffix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasSuffix(FieldTierLabel, v))
}

// TierLabelIsNil applies the IsNil predicate on the "tier_label" field.
func TierLabelIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldTierLabel))
}

// TierLabelNotNil applies the NotNil predicate on the "tier_label" field.
func TierLabelNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldTierLabel))
}

// TierLabelEqualFold applies the EqualFold predicate on the "tier_label" field.
func TierLabelEqualFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEqualFold(FieldTierLabel, v))
}

// TierLabelContainsFold applies the ContainsFold predicate on the "tier_label" field.
func TierLabelContainsFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContainsFold(FieldTierLabel, v))
}

// AvailabilityEQ applies the EQ predicate on the "availability" field.
func AvailabilityEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldAvailability, v))
}

// AvailabilityNEQ applies the NEQ predicate on the "availability" field.
func AvailabilityNEQ(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldAvailability, v))
}

// AvailabilityIn applies the In predicate on the "availability" field.
func AvailabilityIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldAvailability, vs...))
}

// AvailabilityNotIn applies the NotIn predicate on the "availability" field.
func AvailabilityNotIn(vs ...string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldAvailability, vs...))
}

// AvailabilityGT applies the GT predicate on the "availability" field.
func AvailabilityGT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldAvailability, v))
}

// AvailabilityGTE applies the GTE predicate on the "availability" field.
func AvailabilityGTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldAvailability, v))
}

// AvailabilityLT applies the LT predicate on the "availability" field.
func AvailabilityLT(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldAvailability, v))
}

// AvailabilityLTE applies the LTE predicate on the "availability" field.
func AvailabilityLTE(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldAvailability, v))
}

// AvailabilityContains applies the Contains predicate on the "availability" field.
func AvailabilityContains(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContains(FieldAvailability, v))
}

// AvailabilityHasPrefix applies the HasPrefix predicate on the "availability" field.
func AvailabilityHasPrefix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasPrefix(FieldAvailability, v))
}

// AvailabilityHasSuffix applies the HasSuffix predicate on the "availability" field.
func AvailabilityHasSuffix(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldHasSuffix(FieldAvailability, v))
}

// AvailabilityIsNil applies the IsNil predicate on the "availability" field.
func AvailabilityIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldAvailability))
}

// AvailabilityNotNil applies the NotNil predicate on the "availability" field.
func AvailabilityNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldAvailability))
}

// AvailabilityEqualFold applies the EqualFold predicate on the "availability" field.
func AvailabilityEqualFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEqualFold(FieldAvailability, v))
}

// AvailabilityContainsFold applies the ContainsFold predicate on the "availability" field.
func AvailabilityContainsFold(v string) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldContainsFold(FieldAvailability, v))
}

// InputRateEQ applies the EQ predicate on the "input_rate" field.
func InputRateEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldInputRate, v))
}

// InputRateNEQ applies the NEQ predicate on the "input_rate" field.
func InputRateNEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldInputRate, v))
}

// InputRateIn applies the In predicate on the "input_rate" field.
func InputRateIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldInputRate, vs...))
}

// InputRateNotIn applies the NotIn predicate on the "input_rate" field.
func InputRateNotIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldInputRate, vs...))
}

// InputRateGT applies the GT predicate on the "input_rate" field.
func InputRateGT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldInputRate, v))
}

// InputRateGTE applies the GTE predicate on the "input_rate" field.
func InputRateGTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldInputRate, v))
}

// InputRateLT applies the LT predicate on the "input_rate" field.
func InputRateLT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldInputRate, v))
}

// InputRateLTE applies the LTE predicate on the "input_rate" field.
func InputRateLTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldInputRate, v))
}

// InputRateIsNil applies the IsNil predicate on the "input_rate" field.
func InputRateIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldInputRate))
}

// InputRateNotNil applies the NotNil predicate on the "input_rate" field.
func InputRateNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldInputRate))
}

// OutputRateEQ applies the EQ predicate on the "output_rate" field.
func OutputRateEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldOutputRate, v))
}

// OutputRateNEQ applies the NEQ predicate on the "output_rate" field.
func OutputRateNEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldOutputRate, v))
}

// OutputRateIn applies the In predicate on the "output_rate" field.
func OutputRateIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldOutputRate, vs...))
}

// OutputRateNotIn applies the NotIn predicate on the "output_rate" field.
func OutputRateNotIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldOutputRate, vs...))
}

// OutputRateGT applies the GT predicate on the "output_rate" field.
func OutputRateGT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldOutputRate, v))
}

// OutputRateGTE applies the GTE predicate on the "output_rate" field.
func OutputRateGTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldOutputRate, v))
}

// OutputRateLT applies the LT predicate on the "output_rate" field.
func OutputRateLT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldOutputRate, v))
}

// OutputRateLTE applies the LTE predicate on the "output_rate" field.
func OutputRateLTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldOutputRate, v))
}

// OutputRateIsNil applies the IsNil predicate on the "output_rate" field.
func OutputRateIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldOutputRate))
}

// OutputRateNotNil applies the NotNil predicate on the "output_rate" field.
func OutputRateNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldOutputRate))
}

// CachedReadRateEQ applies the EQ predicate on the "cached_read_rate" field.
func CachedReadRateEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldCachedReadRate, v))
}

// CachedReadRateNEQ applies the NEQ predicate on the "cached_read_rate" field.
func CachedReadRateNEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldCachedReadRate, v))
}

// CachedReadRateIn applies the In predicate on the "cached_read_rate" field.
func CachedReadRateIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldCachedReadRate, vs...))
}

// CachedReadRateNotIn applies the NotIn predicate on the "cached_read_rate" field.
func CachedReadRateNotIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldCachedReadRate, vs...))
}

// CachedReadRateGT applies the GT predicate on the "cached_read_rate" field.
func CachedReadRateGT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldCachedReadRate, v))
}

// CachedReadRateGTE applies the GTE predicate on the "cached_read_rate" field.
func CachedReadRateGTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldCachedReadRate, v))
}

// CachedReadRateLT applies the LT predicate on the "cached_read_rate" field.
func CachedReadRateLT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldCachedReadRate, v))
}

// CachedReadRateLTE applies the LTE predicate on the "cached_read_rate" field.
func CachedReadRateLTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldCachedReadRate, v))
}

// CachedReadRateIsNil applies the IsNil predicate on the "cached_read_rate" field.
func CachedReadRateIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldCachedReadRate))
}

// CachedReadRateNotNil applies the NotNil predicate on the "cached_read_rate" field.
func CachedReadRateNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldCachedReadRate))
}

// CachedWriteRateEQ applies the EQ predicate on the "cached_write_rate" field.
func CachedWriteRateEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldCachedWriteRate, v))
}

// CachedWriteRateNEQ applies the NEQ predicate on the "cached_write_rate" field.
func CachedWriteRateNEQ(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldCachedWriteRate, v))
}

// CachedWriteRateIn applies the In predicate on the "cached_write_rate" field.
func CachedWriteRateIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldCachedWriteRate, vs...))
}

// CachedWriteRateNotIn applies the NotIn predicate on the "cached_write_rate" field.
func CachedWriteRateNotIn(vs ...float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldCachedWriteRate, vs...))
}

// CachedWriteRateGT applies the GT predicate on the "cached_write_rate" field.
func CachedWriteRateGT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldCachedWriteRate, v))
}

// CachedWriteRateGTE applies the GTE predicate on the "cached_write_rate" field.
func CachedWriteRateGTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldCachedWriteRate, v))
}

// CachedWriteRateLT applies the LT predicate on the "cached_write_rate" field.
func CachedWriteRateLT(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldCachedWriteRate, v))
}

// CachedWriteRateLTE applies the LTE predicate on the "cached_write_rate" field.
func CachedWriteRateLTE(v float64) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldCachedWriteRate, v))
}

// CachedWriteRateIsNil applies the IsNil predicate on the "cached_write_rate" field.
func CachedWriteRateIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldCachedWriteRate))
}

// CachedWriteRateNotNil applies the NotNil predicate on the "cached_write_rate" field.
func CachedWriteRateNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldCachedWriteRate))
}

// CacheCapabilitiesIsNil applies the IsNil predicate on the "cache_capabilities" field.
func CacheCapabilitiesIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldCacheCapabilities))
}

// CacheCapabilitiesNotNil applies the NotNil predicate on the "cache_capabilities" field.
func CacheCapabilitiesNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldCacheCapabilities))
}

// EffectiveFromEQ applies the EQ predicate on the "effective_from" field.
func EffectiveFromEQ(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldEffectiveFrom, v))
}

// EffectiveFromNEQ applies the NEQ predicate on the "effective_from" field.
func EffectiveFromNEQ(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldEffectiveFrom, v))
}

// EffectiveFromIn applies the In predicate on the "effective_from" field.
func EffectiveFromIn(vs ...time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromNotIn applies the NotIn predicate on the "effective_from" field.
func EffectiveFromNotIn(vs ...time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldEffectiveFrom, vs...))
}

// EffectiveFromGT applies the GT predicate on the "effective_from" field.
func EffectiveFromGT(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldEffectiveFrom, v))
}

// EffectiveFromGTE applies the GTE predicate on the "effective_from" field.
func EffectiveFromGTE(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldEffectiveFrom, v))
}

// EffectiveFromLT applies the LT predicate on the "effective_from" field.
func EffectiveFromLT(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldEffectiveFrom, v))
}

// EffectiveFromLTE applies the LTE predicate on the "effective_from" field.
func EffectiveFromLTE(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldEffectiveFrom, v))
}

// EffectiveFromIsNil applies the IsNil predicate on the "effective_from" field.
func EffectiveFromIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldEffectiveFrom))
}

// EffectiveFromNotNil applies the NotNil predicate on the "effective_from" field.
func EffectiveFromNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldEffectiveFrom))
}

// EffectiveToEQ applies the EQ predicate on the "effective_to" field.
func EffectiveToEQ(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldEQ(FieldEffectiveTo, v))
}

// EffectiveToNEQ applies the NEQ predicate on the "effective_to" field.
func EffectiveToNEQ(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNEQ(FieldEffectiveTo, v))
}

// EffectiveToIn applies the In predicate on the "effective_to" field.
func EffectiveToIn(vs ...time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIn(FieldEffectiveTo, vs...))
}

// EffectiveToNotIn applies the NotIn predicate on the "effective_to" field.
func EffectiveToNotIn(vs ...time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotIn(FieldEffectiveTo, vs...))
}

// EffectiveToGT applies the GT predicate on the "effective_to" field.
func EffectiveToGT(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGT(FieldEffectiveTo, v))
}

// EffectiveToGTE applies the GTE predicate on the "effective_to" field.
func EffectiveToGTE(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldGTE(FieldEffectiveTo, v))
}

// EffectiveToLT applies the LT predicate on the "effective_to" field.
func EffectiveToLT(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLT(FieldEffectiveTo, v))
}

// EffectiveToLTE applies the LTE predicate on the "effective_to" field.
func EffectiveToLTE(v time.Time) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldLTE(FieldEffectiveTo, v))
}

// EffectiveToIsNil applies the IsNil predicate on the "effective_to" field.
func EffectiveToIsNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldIsNull(FieldEffectiveTo))
}

// EffectiveToNotNil applies the NotNil predicate on the "effective_to" field.
func EffectiveToNotNil() predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.FieldNotNull(FieldEffectiveTo))
}

// HasModel applies the HasEdge predicate on the "model" edge.
func HasModel() predicate.SupplierPricing {
	return predicate.SupplierPricing(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModelWith applies the HasEdge predicate on the "model" edge with a given conditions (other predicates).
func HasModelWith(preds ...predicate.ModelCatalog) predicate.SupplierPricing {
	return predicate.SupplierPricing(func(s *sql.Selector) {
		step := newModelStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupplierPricing) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupplierPricing) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupplierPricing) predicate.SupplierPricing {
	return predicate.SupplierPricing(sql.NotPredicates(p))
}
