// Code generated by ent, DO NOT EDIT.

package modelbalance

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelbalance type in the database.
	Label = "model_balance"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldTokensPurchased holds the string denoting the tokens_purchased field in the database.
	FieldTokensPurchased = "tokens_purchased"
	// FieldTokensConsumed holds the string denoting the tokens_consumed field in the database.
	FieldTokensConsumed = "tokens_consumed"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldUsagePercent holds the string denoting the usage_percent field in the database.
	FieldUsagePercent = "usage_percent"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// Table holds the table name of the modelbalance in the database.
	Table = "model_balances"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "model_balances"
	// ModelInverseTable is the table name for the ModelCatalog entity.
	// It exists in this package in order to avoid circular dependency with the "modelcatalog" package.
	ModelInverseTable = "model_catalog"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_id"
)

// Columns holds all SQL columns for modelbalance fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldModelID,
	FieldTokensPurchased,
	FieldTokensConsumed,
	FieldBalance,
	FieldUsagePercent,
	FieldStatus,
	FieldVersion,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultTokensPurchased holds the default value on creation for the "tokens_purchased" field.
	DefaultTokensPurchased int64
	// DefaultTokensConsumed holds the default value on creation for the "tokens_consumed" field.
	DefaultTokensConsumed int64
	// DefaultBalance holds the default value on creation for the "balance" field.
	DefaultBalance int64
	// DefaultUsagePercent holds the default value on creation for the "usage_percent" field.
	DefaultUsagePercent float64
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultVersion holds the default value on creation for the "version" field.
	DefaultVersion int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the ModelBalance queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByTokensPurchased orders the results by the tokens_purchased field.
func ByTokensPurchased(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensPurchased, opts...).ToFunc()
}

// ByTokensConsumed orders the results by the tokens_consumed field.
func ByTokensConsumed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensConsumed, opts...).ToFunc()
}

// ByBalance orders the results by the balance field.
func ByBalance(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBalance, opts...).ToFunc()
}

// ByUsagePercent orders the results by the usage_percent field.
func ByUsagePercent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsagePercent, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
