// Code generated by ent, DO NOT EDIT.

package modelpricing

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelpricing type in the database.
	Label = "model_pricing"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldModelID holds the string denoting the model_id field in the database.
	FieldModelID = "model_id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldInputRate holds the string denoting the input_rate field in the database.
	FieldInputRate = "input_rate"
	// FieldOutputRate holds the string denoting the output_rate field in the database.
	FieldOutputRate = "output_rate"
	// FieldCachedReadRate holds the string denoting the cached_read_rate field in the database.
	FieldCachedReadRate = "cached_read_rate"
	// FieldCachedWriteRate holds the string denoting the cached_write_rate field in the database.
	FieldCachedWriteRate = "cached_write_rate"
	// FieldContextTier holds the string denoting the context_tier field in the database.
	FieldContextTier = "context_tier"
	// FieldTokensPerDollar holds the string denoting the tokens_per_dollar field in the database.
	FieldTokensPerDollar = "tokens_per_dollar"
	// FieldPctPer1mTokens holds the string denoting the pct_per_1m_tokens field in the database.
	FieldPctPer1mTokens = "pct_per_1m_tokens"
	// FieldEffectiveFrom holds the string denoting the effective_from field in the database.
	FieldEffectiveFrom = "effective_from"
	// FieldEffectiveTo holds the string denoting the effective_to field in the database.
	FieldEffectiveTo = "effective_to"
	// FieldSourceRef holds the string denoting the source_ref field in the database.
	FieldSourceRef = "source_ref"
	// EdgeModel holds the string denoting the model edge name in mutations.
	EdgeModel = "model"
	// Table holds the table name of the modelpricing in the database.
	Table = "model_pricing"
	// ModelTable is the table that holds the model relation/edge.
	ModelTable = "model_pricing"
	// ModelInverseTable is the table name for the ModelCatalog entity.
	// It exists in this package in order to avoid circular dependency with the "modelcatalog" package.
	ModelInverseTable = "model_catalog"
	// ModelColumn is the table column denoting the model relation/edge.
	ModelColumn = "model_id"
)

// Columns holds all SQL columns for modelpricing fields.
var Columns = []string{
	FieldID,
	FieldModelID,
	FieldVersion,
	FieldInputRate,
	FieldOutputRate,
	FieldCachedReadRate,
	FieldCachedWriteRate,
	FieldContextTier,
	FieldTokensPerDollar,
	FieldPctPer1mTokens,
	FieldEffectiveFrom,
	FieldEffectiveTo,
	FieldSourceRef,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ContextTierValidator is a validator for the "context_tier" field. It is called by the builders before save.
	ContextTierValidator func(string) error
	// SourceRefValidator is a validator for the "source_ref" field. It is called by the builders before save.
	SourceRefValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the ModelPricing queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByModelID orders the results by the model_id field.
func ByModelID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModelID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByInputRate orders the results by the input_rate field.
func ByInputRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInputRate, opts...).ToFunc()
}

// ByOutputRate orders the results by the output_rate field.
func ByOutputRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutputRate, opts...).ToFunc()
}

// ByCachedReadRate orders the results by the cached_read_rate field.
func ByCachedReadRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedReadRate, opts...).ToFunc()
}

// ByCachedWriteRate orders the results by the cached_write_rate field.
func ByCachedWriteRate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCachedWriteRate, opts...).ToFunc()
}

// ByContextTier orders the results by the context_tier field.
func ByContextTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextTier, opts...).ToFunc()
}

// ByTokensPerDollar orders the results by the tokens_per_dollar field.
func ByTokensPerDollar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensPerDollar, opts...).ToFunc()
}

// ByPctPer1mTokens orders the results by the pct_per_1m_tokens field.
func ByPctPer1mTokens(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPctPer1mTokens, opts...).ToFunc()
}

// ByEffectiveFrom orders the results by the effective_from field.
func ByEffectiveFrom(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveFrom, opts...).ToFunc()
}

// ByEffectiveTo orders the results by the effective_to field.
func ByEffectiveTo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEffectiveTo, opts...).ToFunc()
}

// BySourceRef orders the results by the source_ref field.
func BySourceRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceRef, opts...).ToFunc()
}

// ByModelField orders the results by model field.
func ByModelField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModelStep(), sql.OrderByField(field, opts...))
	}
}
func newModelStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModelInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ModelTable, ModelColumn),
	)
}
