// Code generated by ent, DO NOT EDIT.

package modelcatalog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the modelcatalog type in the database.
	Label = "model_catalog"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldCanonicalName holds the string denoting the canonical_name field in the database.
	FieldCanonicalName = "canonical_name"
	// FieldPublicName holds the string denoting the public_name field in the database.
	FieldPublicName = "public_name"
	// FieldContextWindow holds the string denoting the context_window field in the database.
	FieldContextWindow = "context_window"
	// FieldSourceSuppliers holds the string denoting the source_suppliers field in the database.
	FieldSourceSuppliers = "source_suppliers"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// EdgePricing holds the string denoting the pricing edge name in mutations.
	EdgePricing = "pricing"
	// EdgeSupplierPricing holds the string denoting the supplier_pricing edge name in mutations.
	EdgeSupplierPricing = "supplier_pricing"
	// EdgeBalances holds the string denoting the balances edge name in mutations.
	EdgeBalances = "balances"
	// Table holds the table name of the modelcatalog in the database.
	Table = "model_catalog"
	// PricingTable is the table that holds the pricing relation/edge.
	PricingTable = "model_pricing"
	// PricingInverseTable is the table name for the ModelPricing entity.
	// It exists in this package in order to avoid circular dependency with the "modelpricing" package.
	PricingInverseTable = "model_pricing"
	// PricingColumn is the table column denoting the pricing relation/edge.
	PricingColumn = "model_id"
	// SupplierPricingTable is the table that holds the supplier_pricing relation/edge.
	SupplierPricingTable = "supplier_pricing"
	// SupplierPricingInverseTable is the table name for the SupplierPricing entity.
	// It exists in this package in order to avoid circular dependency with the "supplierpricing" package.
	SupplierPricingInverseTable = "supplier_pricing"
	// SupplierPricingColumn is the table column denoting the supplier_pricing relation/edge.
	SupplierPricingColumn = "model_id"
	// BalancesTable is the table that holds the balances relation/edge.
	BalancesTable = "model_balances"
	// BalancesInverseTable is the table name for the ModelBalance entity.
	// It exists in this package in order to avoid circular dependency with the "modelbalance" package.
	BalancesInverseTable = "model_balances"
	// BalancesColumn is the table column denoting the balances relation/edge.
	BalancesColumn = "model_id"
)

// Columns holds all SQL columns for modelcatalog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldCanonicalName,
	FieldPublicName,
	FieldContextWindow,
	FieldSourceSuppliers,
	FieldStatus,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// CanonicalNameValidator is a validator for the "canonical_name" field. It is called by the builders before save.
	CanonicalNameValidator func(string) error
	// PublicNameValidator is a validator for the "public_name" field. It is called by the builders before save.
	PublicNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the ModelCatalog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByCanonicalName orders the results by the canonical_name field.
func ByCanonicalName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanonicalName, opts...).ToFunc()
}

// ByPublicName orders the results by the public_name field.
func ByPublicName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPublicName, opts...).ToFunc()
}

// ByContextWindow orders the results by the context_window field.
func ByContextWindow(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContextWindow, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByPricingCount orders the results by pricing count.
func ByPricingCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPricingStep(), opts...)
	}
}

// ByPricing orders the results by pricing terms.
func ByPricing(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPricingStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySupplierPricingCount orders the results by supplier_pricing count.
func BySupplierPricingCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSupplierPricingStep(), opts...)
	}
}

// BySupplierPricing orders the results by supplier_pricing terms.
func BySupplierPricing(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSupplierPricingStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBalancesCount orders the results by balances count.
func ByBalancesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBalancesStep(), opts...)
	}
}

// ByBalances orders the results by balances terms.
func ByBalances(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBalancesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPricingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PricingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PricingTable, PricingColumn),
	)
}
func newSupplierPricingStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SupplierPricingInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SupplierPricingTable, SupplierPricingColumn),
	)
}
func newBalancesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BalancesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BalancesTable, BalancesColumn),
	)
}
