// Code generated by ent, DO NOT EDIT.

package modelcatalog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldUpdatedAt, v))
}

// CanonicalName applies equality check predicate on the "canonical_name" field. It's identical to CanonicalNameEQ.
func CanonicalName(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldCanonicalName, v))
}

// PublicName applies equality check predicate on the "public_name" field. It's identical to PublicNameEQ.
func PublicName(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldPublicName, v))
}

// ContextWindow applies equality check predicate on the "context_window" field. It's identical to ContextWindowEQ.
func ContextWindow(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldContextWindow, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldUpdatedAt, v))
}

// CanonicalNameEQ applies the EQ predicate on the "canonical_name" field.
func CanonicalNameEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldCanonicalName, v))
}

// CanonicalNameNEQ applies the NEQ predicate on the "canonical_name" field.
func CanonicalNameNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldCanonicalName, v))
}

// CanonicalNameIn applies the In predicate on the "canonical_name" field.
func CanonicalNameIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldCanonicalName, vs...))
}

// CanonicalNameNotIn applies the NotIn predicate on the "canonical_name" field.
func CanonicalNameNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldCanonicalName, vs...))
}

// CanonicalNameGT applies the GT predicate on the "canonical_name" field.
func CanonicalNameGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldCanonicalName, v))
}

// CanonicalNameGTE applies the GTE predicate on the "canonical_name" field.
func CanonicalNameGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldCanonicalName, v))
}

// CanonicalNameLT applies the LT predicate on the "canonical_name" field.
func CanonicalNameLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldCanonicalName, v))
}

// CanonicalNameLTE applies the LTE predicate on the "canonical_name" field.
func CanonicalNameLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldCanonicalName, v))
}

// CanonicalNameContains applies the Contains predicate on the "canonical_name" field.
func CanonicalNameContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldCanonicalName, v))
}

// CanonicalNameHasPrefix applies the HasPrefix predicate on the "canonical_name" field.
func CanonicalNameHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldCanonicalName, v))
}

// CanonicalNameHasSuffix applies the HasSuffix predicate on the "canonical_name" field.
func CanonicalNameHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldCanonicalName, v))
}

// CanonicalNameEqualFold applies the EqualFold predicate on the "canonical_name" field.
func CanonicalNameEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldCanonicalName, v))
}

// CanonicalNameContainsFold applies the ContainsFold predicate on the "canonical_name" field.
func CanonicalNameContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldCanonicalName, v))
}

// PublicNameEQ applies the EQ predicate on the "public_name" field.
func PublicNameEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldPublicName, v))
}

// PublicNameNEQ applies the NEQ predicate on the "public_name" field.
func PublicNameNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldPublicName, v))
}

// PublicNameIn applies the In predicate on the "public_name" field.
func PublicNameIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldPublicName, vs...))
}

// PublicNameNotIn applies the NotIn predicate on the "public_name" field.
func PublicNameNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldPublicName, vs...))
}

// PublicNameGT applies the GT predicate on the "public_name" field.
func PublicNameGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldPublicName, v))
}

// PublicNameGTE applies the GTE predicate on the "public_name" field.
func PublicNameGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldPublicName, v))
}

// PublicNameLT applies the LT predicate on the "public_name" field.
func PublicNameLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldPublicName, v))
}

// PublicNameLTE applies the LTE predicate on the "public_name" field.
func PublicNameLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldPublicName, v))
}

// PublicNameContains applies the Contains predicate on the "public_name" field.
func PublicNameContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldPublicName, v))
}

// PublicNameHasPrefix applies the HasPrefix predicate on the "public_name" field.
func PublicNameHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldPublicName, v))
}

// PublicNameHasSuffix applies the HasSuffix predicate on the "public_name" field.
func PublicNameHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldPublicName, v))
}

// PublicNameEqualFold applies the EqualFold predicate on the "public_name" field.
func PublicNameEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldPublicName, v))
}

// PublicNameContainsFold applies the ContainsFold predicate on the "public_name" field.
func PublicNameContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldPublicName, v))
}

// ContextWindowEQ applies the EQ predicate on the "context_window" field.
func ContextWindowEQ(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldContextWindow, v))
}

// ContextWindowNEQ applies the NEQ predicate on the "context_window" field.
func ContextWindowNEQ(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldContextWindow, v))
}

// ContextWindowIn applies the In predicate on the "context_window" field.
func ContextWindowIn(vs ...int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldContextWindow, vs...))
}

// ContextWindowNotIn applies the NotIn predicate on the "context_window" field.
func ContextWindowNotIn(vs ...int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldContextWindow, vs...))
}

// ContextWindowGT applies the GT predicate on the "context_window" field.
func ContextWindowGT(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldContextWindow, v))
}

// ContextWindowGTE applies the GTE predicate on the "context_window" field.
func ContextWindowGTE(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldContextWindow, v))
}

// ContextWindowLT applies the LT predicate on the "context_window" field.
func ContextWindowLT(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldContextWindow, v))
}

// ContextWindowLTE applies the LTE predicate on the "context_window" field.
func ContextWindowLTE(v int64) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldContextWindow, v))
}

// ContextWindowIsNil applies the IsNil predicate on the "context_window" field.
func ContextWindowIsNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIsNull(FieldContextWindow))
}

// ContextWindowNotNil applies the NotNil predicate on the "context_window" field.
func ContextWindowNotNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotNull(FieldContextWindow))
}

// SourceSuppliersIsNil applies the IsNil predicate on the "source_suppliers" field.
func SourceSuppliersIsNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIsNull(FieldSourceSuppliers))
}

// SourceSuppliersNotNil applies the NotNil predicate on the "source_suppliers" field.
func SourceSuppliersNotNil() predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotNull(FieldSourceSuppliers))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.FieldContainsFold(FieldStatus, v))
}

// HasPricing applies the HasEdge predicate on the "pricing" edge.
func HasPricing() predicate.ModelCatalog {
	return predicate.ModelCatalog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, PricingTable, PricingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPricingWith applies the HasEdge predicate on the "pricing" edge with a given conditions (other predicates).
func HasPricingWith(preds ...predicate.ModelPricing) predicate.ModelCatalog {
	return predicate.ModelCatalog(func(s *sql.Selector) {
		step := newPricingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSupplierPricing applies the HasEdge predicate on the "supplier_pricing" edge.
func HasSupplierPricing() predicate.ModelCatalog {
	return predicate.ModelCatalog(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SupplierPricingTable, SupplierPricingColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSupplierPricingWith applies the HasEdge predicate on the "supplier_pricing" edge with a given conditions (other predicates).
func HasSupplierPricingWith(preds ...predicate.SupplierPricing) predicate.ModelCatalog {
	return predicate.ModelCatalog(func(s *sql.Selector) {
		step := newSupplierPricingStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ModelCatalog) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ModelCatalog) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ModelCatalog) predicate.ModelCatalog {
	return predicate.ModelCatalog(sql.NotPredicates(p))
}
